package br.gov.mg.tce.business;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;

import javax.ejb.EJB;
import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.NoResultException;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import br.gov.mg.tce.enumerator.IndSimNaoEnum;
import br.gov.mg.tce.enumerator.IndSituacaoCertidaoEnum;
import br.gov.mg.tce.facade.SiaceBOLocal;
import br.gov.mg.tce.facade.SicomBOLocal;
import br.gov.mg.tce.model.CertidaoCompetenciaTributaria;
import br.gov.mg.tce.model.CertidaoLimites;
import br.gov.mg.tce.model.CertidaoOperacaoCredito;
import br.gov.mg.tce.model.OperacaoCreditoDados;
import br.gov.mg.tce.util.Constantes;
import br.gov.mg.tcemg.util.DateUtil;

@Stateless(name = "SiaceBO", mappedName = "SiaceBO")
public class SiaceBO implements SiaceBOLocal {

//    @PersistenceContext(unitName = "SIACELRF")
	private EntityManager entityManagerSIACE;
    
//    @PersistenceContext(unitName = "SIACEPCA2013")
	private EntityManager entityManagerSIACE2013;
    
    @EJB
    private SicomBOLocal sicomBO;

	@Override
	@SuppressWarnings("rawtypes")
	public List<OperacaoCreditoDados> consultarDadosCertidaoOperacaoCredito(CertidaoOperacaoCredito certidaoOperacaoCredito) {

		Long codMunicipioIbge = certidaoOperacaoCredito.getCodMunicipio();
		Integer ultimoExercicioParecerPrevio = certidaoOperacaoCredito.getNumUltExercAna();
		List<OperacaoCreditoDados> creditoDados = new LinkedList<OperacaoCreditoDados>();
		
		String codigoIBGE = "'" + codMunicipioIbge.toString() + "'";
		String sqlRelatorioCertidaoOperacaoCredito = getSQLRelatorioCertidaoOperacaoCredito(codigoIBGE, ultimoExercicioParecerPrevio);
		Query query = entityManagerSIACE.createNativeQuery(sqlRelatorioCertidaoOperacaoCredito.toString());
		List resultList = query.getResultList();
		if(resultList != null && !resultList.isEmpty()){
			
			for (Object object : resultList) {
				
				Object[] lrfArray = (Object[]) object;
				OperacaoCreditoDados operacaoCreditoDados = new OperacaoCreditoDados();
				Date date = (Date) lrfArray[1];
				operacaoCreditoDados.setNumExercicio(DateUtil.getAno(date));
				operacaoCreditoDados.setDatBase12(IndSimNaoEnum.S);
				operacaoCreditoDados.setVlrRclExecutivo(new BigDecimal(lrfArray[2].toString().trim()));
				operacaoCreditoDados.setVlrRecOperacaoCredito(new BigDecimal(lrfArray[3].toString().trim()));
				operacaoCreditoDados.setVlrDespesaCapitalDotIni(new BigDecimal(lrfArray[4].toString().trim()));
				operacaoCreditoDados.setVlrDespesaTotPessoalExec(new BigDecimal(lrfArray[5].toString().trim()));
				operacaoCreditoDados.setPctDespesaTotPessoalExec(new BigDecimal(lrfArray[6].toString().trim()));
				operacaoCreditoDados.setVlrDespesaTotPessoalLeg(new BigDecimal(lrfArray[7].toString().trim()));
				operacaoCreditoDados.setPctDespesaTotPessoalLeg(new BigDecimal(lrfArray[8].toString().trim()));
				operacaoCreditoDados.setDtPublicacaoRREO12((Date) lrfArray[9]);
				operacaoCreditoDados.setDtPublicacaoRGF12((Date) lrfArray[9]);
				operacaoCreditoDados.setSitPublicacao((String) lrfArray[10]);
				if("optante".equalsIgnoreCase((String) lrfArray[11])){
					operacaoCreditoDados.setIndOpcao12(IndSimNaoEnum.S);
				}else{
					operacaoCreditoDados.setIndOpcao12(IndSimNaoEnum.N);
				}
				
				if(!setInfoOperacaoCreditoInstFinanc(certidaoOperacaoCredito, operacaoCreditoDados, codigoIBGE)){
					continue;
				}
				
				creditoDados.add(operacaoCreditoDados);
			}
		}
		
		return creditoDados;
	}
	
	private boolean setInfoOperacaoCreditoInstFinanc(CertidaoOperacaoCredito certidaoOperacaoCredito, OperacaoCreditoDados operacaoCreditoDados, String codigoIBGE) {

		boolean isPreencherInfoOperacaoCredito = true;
		int anoBase = operacaoCreditoDados.getNumExercicio();
		
		if(anoBase >= 2000 && anoBase <= 2013){
			isPreencherInfoOperacaoCredito = setInfoOperacaoCreditoInstFinancSiace(operacaoCreditoDados, codigoIBGE, anoBase);
		}else if(anoBase == 2014){
			operacaoCreditoDados.setIndContratacaoOp(Boolean.valueOf(certidaoOperacaoCredito.getIndContratacaoOP2014().getLabel()));
			operacaoCreditoDados.setIndRealizacaoOp(Boolean.valueOf(certidaoOperacaoCredito.getIndRealizacaoOP2014().getLabel()));
		}else if(anoBase == 2015){
			operacaoCreditoDados.setIndContratacaoOp(Boolean.valueOf(certidaoOperacaoCredito.getIndContratacaoOP2015().getLabel()));
			operacaoCreditoDados.setIndRealizacaoOp(Boolean.valueOf(certidaoOperacaoCredito.getIndRealizacaoOP2015().getLabel()));
		}else if(anoBase >= 2016){
//			isPreencherInfoOperacaoCredito = sicomBO.setInfoOperacaoCreditoInstFinanc(anoBase, certidaoOperacaoCredito.getCodMunicipio(), operacaoCreditoDados);
		}
		
		return isPreencherInfoOperacaoCredito;
	}

	private boolean setInfoOperacaoCreditoInstFinancSiace(OperacaoCreditoDados operacaoCreditoDados, String codigoIBGE, int anoBase) {
		
		boolean isPreencherInfoOperacaoCredito = true;
		try {
			String sql;
			Query query = null;
			switch (anoBase) {
			
			case 2013:
				sql = getSQLInfoOperacaoCreditoInstFinanc2012_2013(codigoIBGE, anoBase);
				query = entityManagerSIACE2013.createNativeQuery(sql.toString());
				break;
				
			default:
				break;
			}
			
			Object[] result  = (Object[]) query.getSingleResult();
			operacaoCreditoDados.setIndContratacaoOp(Boolean.valueOf(result[5].toString()));
			operacaoCreditoDados.setIndRealizacaoOp(Boolean.valueOf(result[7].toString()));
		} catch (NoResultException e) {
			isPreencherInfoOperacaoCredito = false;
		}
		
		return isPreencherInfoOperacaoCredito;
	}
	
	
	private String getSQLInfoOperacaoCreditoInstFinanc2012_2013(String codigoIBGE, Integer exercicio){
		
		StringBuilder SQL = new StringBuilder();
		SQL.append("SELECT R.NUMEROPROTOCOLO,  ");
		SQL.append("  M.NOME,  ");
		SQL.append("  PJ.CNPJ,  ");
		SQL.append("  M.COD_MUNICIPIO_IBGE,  ");
		SQL.append("  OC.HOUVECONTRATACAOPREENCHIDO, ");
		SQL.append("  OC.HOUVECONTRATACAO,         ");
		SQL.append("  OC.FORAMREALOPVEDADASPREENCHIDO,  ");
		SQL.append("  OC.FORAMREALIZADASOPVEDADAS      ");
		SQL.append("FROM OPERACOESDECREDITO OC  ");
		SQL.append("INNER JOIN PRESTACAODECONTAS PC  ");
		SQL.append("ON OC.IDPRESTACAODECONTAS = PC.ID  ");
		SQL.append("INNER JOIN PESSOAJURIDICA PJ  ");
		SQL.append("ON PC.IDENTIDADEOUORGAOAP = PJ.ID  ");
		SQL.append("INNER JOIN PESSOA P  ");
		SQL.append("ON P.ID = PJ.ID  ");
		SQL.append("INNER JOIN MUNICIPIO M  ");
		SQL.append("ON M.ID = P.IDMUNICIPIO  ");
		SQL.append("INNER JOIN ANALISEANUAL AN  ");
		SQL.append("ON AN.IDPCAPRESENTADA = PC.ID  ");
		SQL.append("INNER JOIN REMESSA R  ");
		SQL.append("ON R.IDPRESTACAODECONTAS = PC.ID  ");
		SQL.append("WHERE PC.TRABALHO        = 'N'  ");
		SQL.append("AND PC.ATUAL             = 'S'  ");
		SQL.append("AND AN.EULTIMAANALISE    = 'S'  ");
		SQL.append("AND PC.EXERCICIO         =  ").append(exercicio);
		SQL.append(" AND M.COD_MUNICIPIO_IBGE =  ").append(codigoIBGE);
		SQL.append(" ORDER BY M.NOME ASC"); 
		return SQL.toString();
	}

	private String getSQLRelatorioCertidaoOperacaoCredito(String codigoIBGE, Integer ultimoExercicioParecerPrevio){
		
		StringBuilder SQL = new StringBuilder();
		
		SQL.append("SELECT * FROM ( ");
		SQL.append("SELECT NOMEDOMUNICIPIO,  ");
		SQL.append("  DATABASEREMESSA,  ");
		SQL.append("  TO_CHAR(RCLEXECUTIVO, '999999999999.99')                                                                                                                                                                                                                                                                                                                                                                                 AS RCLEXECUTIVO,  ");
		SQL.append("  TO_CHAR(OPERACOESCREDITOPREVINICIAL, '999999999999.99')                                                                                                                                                                                                                                                                                                                                                                  AS OPERACOESCREDITOPREVINICIAL,  ");
		SQL.append("  TO_CHAR(( DESPESACAPITAL.DESPESAINVESTIMENTOS + DESPESACAPITAL.DESPESAINVFINANCEIRAS + DESPESACAPITAL.DESPESAAMORTDIVINT + DESPESACAPITAL.DESPESAAMORTDIVEXT + DESPESACAPITAL.DESPESAAMORTREFDIVMOB + DESPESACAPITAL.AQUISICAOTITULOS + DESPESACAPITAL.CONCESSAOEMPRESTIMOS + DESPESACAPITAL.INCENTIVOCONTRIBUINTE + DESPESACAPITAL.INCENTIVOINSTFINANCEIRA + DESPESACAPITAL.OUTRASDESPESASCAPITAL ), '999999999999.99') AS DESPESACAPITALDOTACAOINICIAL,  ");
		SQL.append("  TO_CHAR(DESPESATOTALPESSOALEXECUTIVO, '999999999999.99')                                                                                                                                                                                                                                                                                                                                                                 AS DESPESATOTALPESSOALEXECUTIVO,  ");
		SQL.append("  TO_CHAR(DESPESATOTALPESSOALEXECUTIVO/RCLEXECUTIVO*100, '999999999999.99')                                                                                                                                                                                                                                                                                                                                                AS PORCDESPTOTALPESSOALEXEC,  ");
		SQL.append("  TO_CHAR(DESPESATOTALPESSOALLEG, '999999999999.99')                                                                                                                                                                                                                                                                                                                                                                       AS DESPESATOTALPESSOALLEG,  ");
		SQL.append("  TO_CHAR(DESPESATOTALPESSOALLEG/RCLEXECUTIVO*100, '999999999999.99')                                                                                                                                                                                                                                                                                                                                                      AS PORCDESPTOTALPESSOALLEG,  ");
		SQL.append("  DATAPUBLICACAO,  ");
		SQL.append("  SITUACAOPUBLICACAO,  ");
		SQL.append("  OPCAOSEMESTRALIDADE  ");
		SQL.append("FROM  ");
		SQL.append("  (SELECT NOMEDOMUNICIPIO,  ");
		SQL.append("    DATABASEREMESSA,  ");
		SQL.append("    RCLEXECUTIVO,  ");
		SQL.append("    OPERACOESCREDITOPREVINICIAL,  ");
		SQL.append("    DESPESATOTALPESSOALEXECUTIVO,  ");
		SQL.append("    DESPESATOTALPESSOALLEG,  ");
		SQL.append("    DATAPUBLICACAO,  ");
		SQL.append("    SITUACAOPUBLICACAO,  ");
		SQL.append("    OPCAOSEMESTRALIDADE,  ");
		SQL.append("    MAX(EXECUCAOORCAMENTARIA.ID) AS IDDAEXECUCAOORCAMENTARIA  ");
		SQL.append("  FROM  ");
		SQL.append("    (SELECT NOMEDOMUNICIPIO,  ");
		SQL.append("      DATABASEREMESSA,  ");
		SQL.append("      SUM(RECEITACORRENTELIQMENSALPREF) AS RCLEXECUTIVO,  ");
		SQL.append("      SUM(OPERACOESCREDIT)              AS OPERACOESCREDITOPREVINICIAL,  ");
		SQL.append("      SUM(DESPESATOTALPESSOAL)          AS DESPESATOTALPESSOALEXECUTIVO,  ");
		SQL.append("      SUM(DESPESATOTALPESSOALLEG)       AS DESPESATOTALPESSOALLEG,  ");
		SQL.append("      DATAPUBLICACAO,  ");
		SQL.append("      SITUACAOPUBLICACAO,  ");
		SQL.append("      OPCAOSEMESTRALIDADE,  ");
		SQL.append("      IDDAPRESTACAO  ");
		SQL.append("    FROM  ");
		SQL.append("      (SELECT NOMEDOMUNICIPIO,  ");
		SQL.append("        DATABASEREMESSA,  ");
		SQL.append("        MESEXECUCAO,  ");
		SQL.append("        DATAPUBLICACAO,  ");
		SQL.append("        SITUACAOPUBLICACAO,  ");
		SQL.append("        OPCAOSEMESTRALIDADE,  ");
		SQL.append("        IDDAPRESTACAO,  ");
		SQL.append("        (  ");
		SQL.append("        CASE  ");
		SQL.append("          WHEN DATABASEREMESSA = '31/12/2002'  ");
		SQL.append("          THEN ( RECEITATRIBUTARIA.RECEITACONTMELHORIA +RECEITATRIBUTARIA.RECEITATAXAS +RECEITAIMPOSTOS.VALORITBI +RECEITAIMPOSTOS.VALORISSQN +RECEITAIMPOSTOS.VALORIRRF +RECEITAIMPOSTOS.VALORIPTU +RECEITACORRENTE.RECEITACONTRIBUICOES +RECEITAPATRIMONIAL.RECEITAAPLICACOES +RECEITAPATRIMONIAL.VALOROUTRASRECEITAS +RECEITACORRENTE.RECEITAINDUSTRIAIS +RECEITACORRENTE.RECEITAAGROPECUARIAS +RECEITACORRENTE.RECEITASERVICOS +TRANSFERENCIACORRENTE.COTAPARTEFPM +TRANSFERENCIACORRENTE.COTAPARTEICMS +TRANSFERENCIACORRENTE.COTAPARTEIPVA +TRANSFERENCIACORRENTE.COTAPARTEIPI +TRANSFERENCIACORRENTE.TRANSFERENCIAFUNDEF +TRANSFERENCIACORRENTE.OUTRASTRANSFERENCIAS +TRANSFERENCIACORRENTE.CONVENIOS +RECEITACORRENTE.OUTRASRECEITASCORRENTES -EXCLUSAORECEITA.CONTSERVPREVPROP -EXCLUSAORECEITA.COMPENSREGPREV -EXCLUSAORECEITA.OUTRASDUPLICIDADES -EXCLUSAORECEITA.CONTPATRONALPREVPROP -TRANSFINTRAGOVERNAMENTAL.TRANSFFUNDACOES -TRANSFINTRAGOVERNAMENTAL.TRANSFAUTARQUIAS -TRANSFINTRAGOVERNAMENTAL.TRANSFEMPESTDEP  ");
		SQL.append("                                                       - TRANSFINTRAGOVERNAMENTAL.TRANSFDEMAISENT )  ");
		SQL.append("          ELSE ( RECEITATRIBUTARIA.RECEITACONTMELHORIA +RECEITATRIBUTARIA.RECEITATAXAS +RECEITAIMPOSTOS.VALORITBI +RECEITAIMPOSTOS.VALORISSQN +RECEITAIMPOSTOS.VALORIRRF +RECEITAIMPOSTOS.VALORIPTU +RECEITACORRENTE.RECEITACONTRIBUICOES +RECEITAPATRIMONIAL.RECEITAAPLICACOES +RECEITAPATRIMONIAL.VALOROUTRASRECEITAS +RECEITACORRENTE.RECEITAINDUSTRIAIS +RECEITACORRENTE.RECEITAAGROPECUARIAS +RECEITACORRENTE.RECEITASERVICOS +TRANSFERENCIACORRENTE.COTAPARTEFPM +TRANSFERENCIACORRENTE.COTAPARTEICMS +TRANSFERENCIACORRENTE.COTAPARTEIPVA +TRANSFERENCIACORRENTE.COTAPARTEIPI +TRANSFERENCIACORRENTE.TRANSFERENCIAFUNDEF +TRANSFERENCIACORRENTE.OUTRASTRANSFERENCIAS +TRANSFERENCIACORRENTE.CONVENIOS +RECEITACORRENTE.OUTRASRECEITASCORRENTES -EXCLUSAORECEITA.CONTSERVPREVPROP -EXCLUSAORECEITA.COMPENSREGPREV -EXCLUSAORECEITA.OUTRASDUPLICIDADES -EXCLUSAORECEITA.CONTPATRONALPREVPROP -TRANSFINTRAGOVERNAMENTAL.TRANSFFUNDACOES -TRANSFINTRAGOVERNAMENTAL.TRANSFAUTARQUIAS -TRANSFINTRAGOVERNAMENTAL.TRANSFEMPESTDEP  ");
		SQL.append("                                                       - TRANSFINTRAGOVERNAMENTAL.TRANSFDEMAISENT -DEDUCAORECEITA.DEDUCAOFUNDEF -RECEITACORRENTE.DEDUCOESRECEITACORRENTE )  ");
		SQL.append("        END )                                                                           AS RECEITACORRENTELIQMENSALPREF,  ");
		SQL.append("        ( OPERACOESCREDITO.RECEITAREFDIVIDA + OPERACOESCREDITO.RECEITAOUTRASOPCREDITO ) AS OPERACOESCREDIT,  ");
		SQL.append("        (  ");
		SQL.append("        CASE  ");
		SQL.append("          WHEN MESEXECUCAO     = 12  ");
		SQL.append("          AND DATABASEREMESSA IN ('31/12/2008', '31/12/2009')  ");
		SQL.append("          THEN  ");
		SQL.append("            CASE  ");
		SQL.append("              WHEN DESPESAMENSALPESSOAL.NADAADECLARAR = 'S'  ");
		SQL.append("              THEN DESPESAMENSALPESSOAL.VENCIMENTOSVANTAGENS + DESPESAMENSALPESSOAL.INATIVOS + DESPESAMENSALPESSOAL.PENSIONISTAS + DESPESAMENSALPESSOAL.SALARIOFAMILIA + DESPESAMENSALPESSOALPREF.SUBSIDIOPREFEITO + DESPESAMENSALPESSOALPREF.SUBSIDIOVICEPREFEITO + DESPESAMENSALPESSOALPREF.SUBSIDIOSECRETARIOSMUNICIPAIS + DESPESAMENSALPESSOAL.OBRIGACOESPATRONAIS + DESPESAMENSALPESSOAL.REPASSEPATRONAL + DESPESAMENSALPESSOAL.SENTENCASJUDICIARIAS + DESPESAMENSALPESSOAL.DESPESASANTCORRESPONDENTE + DESPESAMENSALPESSOAL.DESPESASANTERIORESCOMPETENCIA - DESPESAMENSALPESSOAL.INDENIZACOESDEMISSAO - DESPESAMENSALPESSOAL.INCENTIVOSDEMISSAOVOLUNTARIA - DESPESAMENSALPESSOAL.SENTENCASJUDICIARIASANTERIORES - DESPESAMENSALPESSOAL.INATIVOSFONTECUSTEIOPROPRIA - DESPESAMENSALPESSOAL.DESPEXCLANTERIORAPURACAO  ");
		SQL.append("              ELSE DESPESAMENSALPESSOAL.VENCIMENTOSVANTAGENS + DESPESAMENSALPESSOAL.INATIVOS + DESPESAMENSALPESSOAL.PENSIONISTAS + DESPESAMENSALPESSOAL.SALARIOFAMILIA + DESPESAMENSALPESSOALPREF.SUBSIDIOPREFEITO + DESPESAMENSALPESSOALPREF.SUBSIDIOVICEPREFEITO + DESPESAMENSALPESSOALPREF.SUBSIDIOSECRETARIOSMUNICIPAIS + DESPESAMENSALPESSOAL.OBRIGACOESPATRONAIS + DESPESAMENSALPESSOAL.REPASSEPATRONAL + DESPESAMENSALPESSOAL.SENTENCASJUDICIARIAS + DESPESAMENSALPESSOAL.OUTRASDESPESASPESSOAL + DESPESAMENSALPESSOAL.DESPESASANTCORRESPONDENTE + DESPESAMENSALPESSOAL.DESPESASANTERIORESCOMPETENCIA - DESPESAMENSALPESSOAL.INDENIZACOESDEMISSAO - DESPESAMENSALPESSOAL.INCENTIVOSDEMISSAOVOLUNTARIA - DESPESAMENSALPESSOAL.SENTENCASJUDICIARIASANTERIORES - DESPESAMENSALPESSOAL.INATIVOSFONTECUSTEIOPROPRIA - DESPESAMENSALPESSOAL.DESPEXCLANTERIORAPURACAO  ");
		SQL.append("            END  ");
		SQL.append("          WHEN MESEXECUCAO     = 12  ");
		SQL.append("          AND DATABASEREMESSA IN ('31/12/2011', '31/12/2012', '31/12/2013', '31/12/2014', '31/12/2015', '31/12/2016', '31/12/2017')  ");
		SQL.append("          THEN  ");
		SQL.append("            CASE  ");
		SQL.append("              WHEN DESPESAMENSALPESSOAL.NADAADECLARAR = 'S'  ");
		SQL.append("              THEN DESPESAMENSALPESSOAL.VENCIMENTOSVANTAGENS + DESPESAMENSALPESSOAL.INATIVOS + DESPESAMENSALPESSOAL.PENSIONISTAS + DESPESAMENSALPESSOAL.SALARIOFAMILIA + DESPESAMENSALPESSOALPREF.SUBSIDIOPREFEITO + DESPESAMENSALPESSOALPREF.SUBSIDIOVICEPREFEITO + DESPESAMENSALPESSOALPREF.SUBSIDIOSECRETARIOSMUNICIPAIS + DESPESAMENSALPESSOAL.OBRIGACOESPATRONAIS + DESPESAMENSALPESSOAL.REPASSEPATRONAL + DESPESAMENSALPESSOAL.SENTENCASJUDICIARIAS + DESPESAMENSALPESSOAL.DESPESASANTERIORESCOMPETENCIA - DESPESAMENSALPESSOAL.INDENIZACOESDEMISSAO - DESPESAMENSALPESSOAL.INCENTIVOSDEMISSAOVOLUNTARIA - DESPESAMENSALPESSOAL.SENTENCASJUDICIARIASANTERIORES - DESPESAMENSALPESSOAL.INATIVOSFONTECUSTEIOPROPRIA  ");
		SQL.append("              ELSE DESPESAMENSALPESSOAL.VENCIMENTOSVANTAGENS + DESPESAMENSALPESSOAL.INATIVOS + DESPESAMENSALPESSOAL.PENSIONISTAS + DESPESAMENSALPESSOAL.SALARIOFAMILIA + DESPESAMENSALPESSOALPREF.SUBSIDIOPREFEITO + DESPESAMENSALPESSOALPREF.SUBSIDIOVICEPREFEITO + DESPESAMENSALPESSOALPREF.SUBSIDIOSECRETARIOSMUNICIPAIS + DESPESAMENSALPESSOAL.OBRIGACOESPATRONAIS + DESPESAMENSALPESSOAL.REPASSEPATRONAL + DESPESAMENSALPESSOAL.SENTENCASJUDICIARIAS + DESPESAMENSALPESSOAL.OUTRASDESPESASPESSOAL + DESPESAMENSALPESSOAL.DESPESASANTERIORESCOMPETENCIA - DESPESAMENSALPESSOAL.INDENIZACOESDEMISSAO - DESPESAMENSALPESSOAL.INCENTIVOSDEMISSAOVOLUNTARIA - DESPESAMENSALPESSOAL.SENTENCASJUDICIARIASANTERIORES - DESPESAMENSALPESSOAL.INATIVOSFONTECUSTEIOPROPRIA  ");
		SQL.append("            END  ");
		SQL.append("          ELSE  ");
		SQL.append("            CASE  ");
		SQL.append("              WHEN DESPESAMENSALPESSOAL.NADAADECLARAR = 'S'  ");
		SQL.append("              THEN DESPESAMENSALPESSOAL.VENCIMENTOSVANTAGENS + DESPESAMENSALPESSOAL.INATIVOS + DESPESAMENSALPESSOAL.PENSIONISTAS + DESPESAMENSALPESSOAL.SALARIOFAMILIA + DESPESAMENSALPESSOALPREF.SUBSIDIOPREFEITO + DESPESAMENSALPESSOALPREF.SUBSIDIOVICEPREFEITO + DESPESAMENSALPESSOALPREF.SUBSIDIOSECRETARIOSMUNICIPAIS + DESPESAMENSALPESSOAL.OBRIGACOESPATRONAIS + DESPESAMENSALPESSOAL.REPASSEPATRONAL + DESPESAMENSALPESSOAL.SENTENCASJUDICIARIAS + DESPESAMENSALPESSOAL.DESPESASANTERIORES + DESPESAMENSALPESSOAL.DESPESASANTCORRESPONDENTE + DESPESAMENSALPESSOAL.DESPESASANTERIORESCOMPETENCIA - DESPESAMENSALPESSOAL.INDENIZACOESDEMISSAO - DESPESAMENSALPESSOAL.INCENTIVOSDEMISSAOVOLUNTARIA - DESPESAMENSALPESSOAL.SENTENCASJUDICIARIASANTERIORES - DESPESAMENSALPESSOAL.INATIVOSFONTECUSTEIOPROPRIA - DESPESAMENSALPESSOAL.DESPESASANTERIORESEXCLUSAO - DESPESAMENSALPESSOAL.DESPEXCLANTERIORAPURACAO  ");
		SQL.append("              ELSE DESPESAMENSALPESSOAL.VENCIMENTOSVANTAGENS + DESPESAMENSALPESSOAL.INATIVOS + DESPESAMENSALPESSOAL.PENSIONISTAS + DESPESAMENSALPESSOAL.SALARIOFAMILIA + DESPESAMENSALPESSOALPREF.SUBSIDIOPREFEITO + DESPESAMENSALPESSOALPREF.SUBSIDIOVICEPREFEITO + DESPESAMENSALPESSOALPREF.SUBSIDIOSECRETARIOSMUNICIPAIS + DESPESAMENSALPESSOAL.OBRIGACOESPATRONAIS + DESPESAMENSALPESSOAL.REPASSEPATRONAL + DESPESAMENSALPESSOAL.SENTENCASJUDICIARIAS + DESPESAMENSALPESSOAL.OUTRASDESPESASPESSOAL + DESPESAMENSALPESSOAL.DESPESASANTERIORES + DESPESAMENSALPESSOAL.DESPESASANTCORRESPONDENTE + DESPESAMENSALPESSOAL.DESPESASANTERIORESCOMPETENCIA - DESPESAMENSALPESSOAL.INDENIZACOESDEMISSAO - DESPESAMENSALPESSOAL.INCENTIVOSDEMISSAOVOLUNTARIA - DESPESAMENSALPESSOAL.SENTENCASJUDICIARIASANTERIORES - DESPESAMENSALPESSOAL.INATIVOSFONTECUSTEIOPROPRIA - DESPESAMENSALPESSOAL.DESPESASANTERIORESEXCLUSAO - DESPESAMENSALPESSOAL.DESPEXCLANTERIORAPURACAO  ");
		SQL.append("            END  ");
		SQL.append("        END ) AS DESPESATOTALPESSOAL  ");
		SQL.append("      FROM  ");
		SQL.append("        (SELECT NOMEDOMUNICIPIO,  ");
		SQL.append("          DATABASEREMESSA,  ");
		SQL.append("          EXECUCAOORCAMENTARIA.MES AS MESEXECUCAO,  ");
		SQL.append("          DATAPUBLICACAO,  ");
		SQL.append("          SITUACAOPUBLICACAO,  ");
		SQL.append("          OPCAOSEMESTRALIDADE,  ");
		SQL.append("          MAX(EXECUCAOORCAMENTARIA.ID) AS IDDAEXECUCAOORCAMENTARIA,  ");
		SQL.append("          GESTAOFISCAL.ID              AS IDDAGESTAOFISCAL,  ");
		SQL.append("          IDDAPRESTACAO  ");
		SQL.append("        FROM  ");
		SQL.append("          (SELECT MUNICIPIO.NOME AS NOMEDOMUNICIPIO,  ");
		SQL.append("            PRESTACAO.ID         AS IDDAPRESTACAO,  ");
		SQL.append("            DATABASEREMESSA,  ");
		SQL.append("            REMESSALRF.DATAPUBLICACAO AS DATAPUBLICACAO,  ");
		SQL.append("            (  ");
		SQL.append("            CASE  ");
		SQL.append("              WHEN REMESSALRF.DATAPUBLICACAO > ADD_MONTHS(DATABASEREMESSA, 1)  ");
		SQL.append("              THEN 'Intempestivo'  ");
		SQL.append("              ELSE 'Tempestivo'  ");
		SQL.append("            END ) AS SITUACAOPUBLICACAO,  ");
		SQL.append("            (  ");
		SQL.append("            CASE  ");
		SQL.append("              WHEN OPCAOSEMESTRALIDADE.TIPO = 0  ");
		SQL.append("              THEN 'Não-optante'  ");
		SQL.append("              WHEN STATUSOPCAOSEMESTRALIDADE.TEMOPCAO = 'S'  ");
		SQL.append("              THEN 'Optante'  ");
		SQL.append("              ELSE 'Perdeu o direito de optar'  ");
		SQL.append("            END ) AS OPCAOSEMESTRALIDADE  ");
		SQL.append("          FROM MUNICIPIO  ");
		SQL.append("          INNER JOIN ENTIDADEOUORGAOAP  ");
		SQL.append("          ON MUNICIPIO.IDPREFEITURA = ENTIDADEOUORGAOAP.ID  ");
		SQL.append("          INNER JOIN PRESTACAO  ");
		SQL.append("          ON PRESTACAO.IDENTIDADEOUORGAOAP = ENTIDADEOUORGAOAP.ID  ");
		SQL.append("          INNER JOIN REMESSALRF  ");
		SQL.append("          ON REMESSALRF.IDPRESTACAO = PRESTACAO.ID  ");
		SQL.append("          INNER JOIN OPCAOSEMESTRALIDADE  ");
		SQL.append("          ON OPCAOSEMESTRALIDADE.IDENTIDADEOUORGAOAP = ENTIDADEOUORGAOAP.ID  ");
		SQL.append("          INNER JOIN STATUSOPCAOSEMESTRALIDADE  ");
		SQL.append("          ON OPCAOSEMESTRALIDADE.ID = STATUSOPCAOSEMESTRALIDADE.IDOPCAOSEMESTRALIDADE  ");
		SQL.append("          INNER JOIN  ");
		SQL.append("            (SELECT NOMEMUNICIPIO,  ");
		SQL.append("              MAX(REMESSALRF.ID) AS IDDAREMESSALRF,  ");
		SQL.append("              REMESSALRF.DTBASE  AS DATABASEREMESSA  ");
		SQL.append("            FROM MUNICIPIO  ");
		SQL.append("            INNER JOIN ENTIDADEOUORGAOAP  ");
		SQL.append("            ON MUNICIPIO.IDPREFEITURA = ENTIDADEOUORGAOAP.ID  ");
		SQL.append("            INNER JOIN PRESTACAO  ");
		SQL.append("            ON PRESTACAO.IDENTIDADEOUORGAOAP = ENTIDADEOUORGAOAP.ID  ");
		SQL.append("            INNER JOIN REMESSALRF  ");
		SQL.append("            ON PRESTACAO.ID = REMESSALRF.IDPRESTACAO  ");
		SQL.append("            INNER JOIN  ");
		SQL.append("              (SELECT MUNICIPIO.NOME AS NOMEMUNICIPIO,  ");
		SQL.append("                REMESSALRF.DTBASE DATABASE,  ");
		SQL.append("                MAX(REMESSALRF.DATAENVIO) AS DATAENVIO1  ");
		SQL.append("              FROM MUNICIPIO  ");
		SQL.append("              INNER JOIN ENTIDADEOUORGAOAP  ");
		SQL.append("              ON MUNICIPIO.IDPREFEITURA = ENTIDADEOUORGAOAP.ID  ");
		SQL.append("              INNER JOIN PRESTACAO  ");
		SQL.append("              ON PRESTACAO.IDENTIDADEOUORGAOAP = ENTIDADEOUORGAOAP.ID  ");
		SQL.append("              INNER JOIN REMESSALRF  ");
		SQL.append("              ON PRESTACAO.ID          = REMESSALRF.IDPRESTACAO  ");
		SQL.append("              WHERE REMESSALRF.DTBASE IN ('31/12/2002', '31/12/2003', '31/12/2004', '31/12/2005', '31/12/2006', '31/12/2007', '31/12/2008', '31/12/2009', '31/12/2010', '31/12/2011', '31/12/2012', '31/12/2013', '31/12/2014', '31/12/2015', '31/12/2016', '31/12/2017')  ");
		SQL.append("              AND MUNICIPIO.CODIGOIBGE = ").append(codigoIBGE);
		SQL.append("              GROUP BY MUNICIPIO.NOME,  ");
		SQL.append("                REMESSALRF.DTBASE  ");
		SQL.append("              ORDER BY REMESSALRF.DTBASE  ");
		SQL.append("              ) ON DATAENVIO1 = REMESSALRF.DATAENVIO  ");
		SQL.append("            AND DATABASE      = REMESSALRF.DTBASE  ");
		SQL.append("            AND NOMEMUNICIPIO = MUNICIPIO.NOME  ");
		SQL.append("            GROUP BY NOMEMUNICIPIO,  ");
		SQL.append("              REMESSALRF.DTBASE,  ");
		SQL.append("              DATAENVIO1  ");
		SQL.append("            ORDER BY REMESSALRF.DTBASE  ");
		SQL.append("            ) ON REMESSALRF.ID                   = IDDAREMESSALRF  ");
		SQL.append("          WHERE STATUSOPCAOSEMESTRALIDADE.DTBASE = DATABASEREMESSA  ");
		SQL.append("          )  ");
		SQL.append("        INNER JOIN EXECUCAOORCAMENTARIA  ");
		SQL.append("        ON EXECUCAOORCAMENTARIA.IDPRESTACAOLRFEXECUTIVO = IDDAPRESTACAO  ");
		SQL.append("        INNER JOIN GESTAOFISCAL  ");
		SQL.append("        ON GESTAOFISCAL.IDPRESTACAOLRF = IDDAPRESTACAO  ");
		SQL.append("        AND EXECUCAOORCAMENTARIA.MES   = GESTAOFISCAL.MES  ");
		SQL.append("        AND GESTAOFISCAL.FOIEXCLUIDA   = 'N'  ");
		SQL.append("        GROUP BY NOMEDOMUNICIPIO,  ");
		SQL.append("          DATABASEREMESSA,  ");
		SQL.append("          EXECUCAOORCAMENTARIA.MES,  ");
		SQL.append("          DATAPUBLICACAO,  ");
		SQL.append("          SITUACAOPUBLICACAO,  ");
		SQL.append("          OPCAOSEMESTRALIDADE,  ");
		SQL.append("          IDDAPRESTACAO,  ");
		SQL.append("          GESTAOFISCAL.ID  ");
		SQL.append("        ORDER BY DATABASEREMESSA,  ");
		SQL.append("          EXECUCAOORCAMENTARIA.MES  ");
		SQL.append("        )  ");
		SQL.append("      INNER JOIN EXECUCAOBIMESTRAL  ");
		SQL.append("      ON IDDAEXECUCAOORCAMENTARIA       = EXECUCAOBIMESTRAL.IDEXECUCAOORCAMENTARIA  ");
		SQL.append("      AND EXECUCAOBIMESTRAL.FOIEXCLUIDO = 'N'  ");
		SQL.append("      INNER JOIN EXECUCAORECEITA  ");
		SQL.append("      ON EXECUCAOBIMESTRAL.IDEXECUCAORECEITA = EXECUCAORECEITA.ID  ");
		SQL.append("      INNER JOIN RECEITACORRENTE  ");
		SQL.append("      ON RECEITACORRENTE.IDEXECUCAORECEITA = EXECUCAORECEITA.ID  ");
		SQL.append("      AND TIPORECEITA                      = 4  ");
		SQL.append("      INNER JOIN RECEITATRIBUTARIA  ");
		SQL.append("      ON RECEITATRIBUTARIA.ID = RECEITACORRENTE.IDRECEITATRIBUTARIA  ");
		SQL.append("      INNER JOIN RECEITAIMPOSTOS  ");
		SQL.append("      ON RECEITATRIBUTARIA.IDRECEITAIMPOSTOS = RECEITAIMPOSTOS.ID  ");
		SQL.append("      INNER JOIN RECEITAPATRIMONIAL  ");
		SQL.append("      ON RECEITAPATRIMONIAL.ID = RECEITACORRENTE.IDRECEITAPATRIMONIAL  ");
		SQL.append("      INNER JOIN TRANSFERENCIACORRENTE  ");
		SQL.append("      ON TRANSFERENCIACORRENTE.ID = RECEITACORRENTE.IDTRANSFERENCIACORRENTE  ");
		SQL.append("      INNER JOIN EXCLUSAORECEITA  ");
		SQL.append("      ON EXCLUSAORECEITA.ID = EXECUCAORECEITA.IDEXCLUSAORECEITA  ");
		SQL.append("      INNER JOIN TRANSFINTRAGOVERNAMENTAL  ");
		SQL.append("      ON TRANSFINTRAGOVERNAMENTAL.ID = EXCLUSAORECEITA.IDEXCLUSAORECTRANSFCORRENTE  ");
		SQL.append("      INNER JOIN DEDUCAORECEITA  ");
		SQL.append("      ON DEDUCAORECEITA.IDEXECUCAORECEITA = EXECUCAORECEITA.ID  ");
		SQL.append("      AND DEDUCAORECEITA.TIPORECEITA      = 4  ");
		SQL.append("      INNER JOIN RECEITACAPITAL  ");
		SQL.append("      ON RECEITACAPITAL.IDEXECUCAORECEITA = EXECUCAORECEITA.ID  ");
		SQL.append("      AND RECEITACAPITAL.TIPORECEITA      = 1  ");
		SQL.append("      INNER JOIN OPERACOESCREDITO  ");
		SQL.append("      ON RECEITACAPITAL.IDOPERACOESCREDITO = OPERACOESCREDITO.ID  ");
		SQL.append("      INNER JOIN GESTAOFISCAL  ");
		SQL.append("      ON GESTAOFISCAL.ID = IDDAGESTAOFISCAL  ");
		SQL.append("      INNER JOIN DESPESAMENSALPESSOAL  ");
		SQL.append("      ON DESPESAMENSALPESSOAL.ID = GESTAOFISCAL.IDDESPESAMENSALPESSOAL  ");
		SQL.append("      INNER JOIN DESPESAMENSALPESSOALPREF  ");
		SQL.append("      ON DESPESAMENSALPESSOAL.ID = DESPESAMENSALPESSOALPREF.ID  ");
		SQL.append("      )  ");
		SQL.append("    INNER JOIN  ");
		SQL.append("      (SELECT DATABASEREMESSALEG,  ");
		SQL.append("        MESGESTAO,  ");
		SQL.append("        (  ");
		SQL.append("        CASE  ");
		SQL.append("          WHEN MESGESTAO          = 12  ");
		SQL.append("          AND DATABASEREMESSALEG IN ('31/12/2008', '31/12/2009')  ");
		SQL.append("          THEN  ");
		SQL.append("            CASE  ");
		SQL.append("              WHEN DESPESAMENSALPESSOAL.NADAADECLARAR = 'S'  ");
		SQL.append("              THEN DESPESAMENSALPESSOAL.VENCIMENTOSVANTAGENS + DESPESAMENSALPESSOAL.INATIVOS + DESPESAMENSALPESSOAL.PENSIONISTAS + DESPESAMENSALPESSOAL.SALARIOFAMILIA + DESPESAMENSALPESSOALCAM.SUBSIDIOVEREADORES + DESPESAMENSALPESSOAL.OBRIGACOESPATRONAIS + DESPESAMENSALPESSOAL.REPASSEPATRONAL + DESPESAMENSALPESSOAL.SENTENCASJUDICIARIAS + DESPESAMENSALPESSOAL.DESPESASANTCORRESPONDENTE + DESPESAMENSALPESSOAL.DESPESASANTERIORESCOMPETENCIA - DESPESAMENSALPESSOAL.INDENIZACOESDEMISSAO - DESPESAMENSALPESSOAL.INCENTIVOSDEMISSAOVOLUNTARIA - DESPESAMENSALPESSOAL.SENTENCASJUDICIARIASANTERIORES - DESPESAMENSALPESSOAL.INATIVOSFONTECUSTEIOPROPRIA - DESPESAMENSALPESSOAL.DESPEXCLANTERIORAPURACAO - DESPESAMENSALPESSOAL.CONVOCACAOEXTRAORDINARIA  ");
		SQL.append("              ELSE DESPESAMENSALPESSOAL.VENCIMENTOSVANTAGENS + DESPESAMENSALPESSOAL.INATIVOS + DESPESAMENSALPESSOAL.PENSIONISTAS + DESPESAMENSALPESSOAL.SALARIOFAMILIA + DESPESAMENSALPESSOALCAM.SUBSIDIOVEREADORES + DESPESAMENSALPESSOAL.OBRIGACOESPATRONAIS + DESPESAMENSALPESSOAL.REPASSEPATRONAL + DESPESAMENSALPESSOAL.SENTENCASJUDICIARIAS + DESPESAMENSALPESSOAL.OUTRASDESPESASPESSOAL + DESPESAMENSALPESSOAL.DESPESASANTCORRESPONDENTE + DESPESAMENSALPESSOAL.DESPESASANTERIORESCOMPETENCIA - DESPESAMENSALPESSOAL.INDENIZACOESDEMISSAO - DESPESAMENSALPESSOAL.INCENTIVOSDEMISSAOVOLUNTARIA - DESPESAMENSALPESSOAL.SENTENCASJUDICIARIASANTERIORES - DESPESAMENSALPESSOAL.INATIVOSFONTECUSTEIOPROPRIA - DESPESAMENSALPESSOAL.DESPEXCLANTERIORAPURACAO - DESPESAMENSALPESSOAL.CONVOCACAOEXTRAORDINARIA  ");
		SQL.append("            END  ");
		SQL.append("          WHEN MESGESTAO          = 12  ");
		SQL.append("          AND DATABASEREMESSALEG IN ('31/12/2011', '31/12/2012', '31/12/2013', '31/12/2014', '31/12/2015', '31/12/2016', '31/12/2017')  ");
		SQL.append("          THEN  ");
		SQL.append("            CASE  ");
		SQL.append("              WHEN DESPESAMENSALPESSOAL.NADAADECLARAR = 'S'  ");
		SQL.append("              THEN DESPESAMENSALPESSOAL.VENCIMENTOSVANTAGENS + DESPESAMENSALPESSOAL.INATIVOS + DESPESAMENSALPESSOAL.PENSIONISTAS + DESPESAMENSALPESSOAL.SALARIOFAMILIA + DESPESAMENSALPESSOALCAM.SUBSIDIOVEREADORES + DESPESAMENSALPESSOAL.OBRIGACOESPATRONAIS + DESPESAMENSALPESSOAL.REPASSEPATRONAL + DESPESAMENSALPESSOAL.SENTENCASJUDICIARIAS + DESPESAMENSALPESSOAL.DESPESASANTERIORESCOMPETENCIA - DESPESAMENSALPESSOAL.INDENIZACOESDEMISSAO - DESPESAMENSALPESSOAL.INCENTIVOSDEMISSAOVOLUNTARIA - DESPESAMENSALPESSOAL.SENTENCASJUDICIARIASANTERIORES - DESPESAMENSALPESSOAL.INATIVOSFONTECUSTEIOPROPRIA - DESPESAMENSALPESSOAL.CONVOCACAOEXTRAORDINARIA  ");
		SQL.append("              ELSE DESPESAMENSALPESSOAL.VENCIMENTOSVANTAGENS + DESPESAMENSALPESSOAL.INATIVOS + DESPESAMENSALPESSOAL.PENSIONISTAS + DESPESAMENSALPESSOAL.SALARIOFAMILIA + DESPESAMENSALPESSOALCAM.SUBSIDIOVEREADORES + DESPESAMENSALPESSOAL.OBRIGACOESPATRONAIS + DESPESAMENSALPESSOAL.REPASSEPATRONAL + DESPESAMENSALPESSOAL.SENTENCASJUDICIARIAS + DESPESAMENSALPESSOAL.OUTRASDESPESASPESSOAL + DESPESAMENSALPESSOAL.DESPESASANTERIORESCOMPETENCIA - DESPESAMENSALPESSOAL.INDENIZACOESDEMISSAO - DESPESAMENSALPESSOAL.INCENTIVOSDEMISSAOVOLUNTARIA - DESPESAMENSALPESSOAL.SENTENCASJUDICIARIASANTERIORES - DESPESAMENSALPESSOAL.INATIVOSFONTECUSTEIOPROPRIA - DESPESAMENSALPESSOAL.CONVOCACAOEXTRAORDINARIA  ");
		SQL.append("            END  ");
		SQL.append("          ELSE  ");
		SQL.append("            CASE  ");
		SQL.append("              WHEN DESPESAMENSALPESSOAL.NADAADECLARAR = 'S'  ");
		SQL.append("              THEN DESPESAMENSALPESSOAL.VENCIMENTOSVANTAGENS + DESPESAMENSALPESSOAL.INATIVOS + DESPESAMENSALPESSOAL.PENSIONISTAS + DESPESAMENSALPESSOAL.SALARIOFAMILIA + DESPESAMENSALPESSOALCAM.SUBSIDIOVEREADORES + DESPESAMENSALPESSOAL.OBRIGACOESPATRONAIS + DESPESAMENSALPESSOAL.REPASSEPATRONAL + DESPESAMENSALPESSOAL.SENTENCASJUDICIARIAS + DESPESAMENSALPESSOAL.DESPESASANTERIORES + DESPESAMENSALPESSOAL.DESPESASANTCORRESPONDENTE + DESPESAMENSALPESSOAL.DESPESASANTERIORESCOMPETENCIA - DESPESAMENSALPESSOAL.INDENIZACOESDEMISSAO - DESPESAMENSALPESSOAL.INCENTIVOSDEMISSAOVOLUNTARIA - DESPESAMENSALPESSOAL.SENTENCASJUDICIARIASANTERIORES - DESPESAMENSALPESSOAL.INATIVOSFONTECUSTEIOPROPRIA - DESPESAMENSALPESSOAL.CONVOCACAOEXTRAORDINARIA - DESPESAMENSALPESSOAL.DESPESASANTERIORESEXCLUSAO - DESPESAMENSALPESSOAL.DESPEXCLANTERIORAPURACAO  ");
		SQL.append("              ELSE DESPESAMENSALPESSOAL.VENCIMENTOSVANTAGENS + DESPESAMENSALPESSOAL.INATIVOS + DESPESAMENSALPESSOAL.PENSIONISTAS + DESPESAMENSALPESSOAL.SALARIOFAMILIA + DESPESAMENSALPESSOALCAM.SUBSIDIOVEREADORES + DESPESAMENSALPESSOAL.OBRIGACOESPATRONAIS + DESPESAMENSALPESSOAL.REPASSEPATRONAL + DESPESAMENSALPESSOAL.SENTENCASJUDICIARIAS + DESPESAMENSALPESSOAL.OUTRASDESPESASPESSOAL + DESPESAMENSALPESSOAL.DESPESASANTERIORES + DESPESAMENSALPESSOAL.DESPESASANTCORRESPONDENTE + DESPESAMENSALPESSOAL.DESPESASANTERIORESCOMPETENCIA - DESPESAMENSALPESSOAL.INDENIZACOESDEMISSAO - DESPESAMENSALPESSOAL.INCENTIVOSDEMISSAOVOLUNTARIA - DESPESAMENSALPESSOAL.SENTENCASJUDICIARIASANTERIORES - DESPESAMENSALPESSOAL.INATIVOSFONTECUSTEIOPROPRIA - DESPESAMENSALPESSOAL.CONVOCACAOEXTRAORDINARIA - DESPESAMENSALPESSOAL.DESPESASANTERIORESEXCLUSAO - DESPESAMENSALPESSOAL.DESPEXCLANTERIORAPURACAO  ");
		SQL.append("            END  ");
		SQL.append("        END ) AS DESPESATOTALPESSOALLEG  ");
		SQL.append("      FROM  ");
		SQL.append("        (SELECT DATABASEREMESSALEG,  ");
		SQL.append("          GESTAOFISCAL.MES     AS MESGESTAO,  ");
		SQL.append("          MAX(GESTAOFISCAL.ID) AS IDDAGESTAOFISCAL  ");
		SQL.append("        FROM  ");
		SQL.append("          (SELECT PRESTACAO.ID AS IDDAPRESTACAO,  ");
		SQL.append("            DATABASEREMESSALEG  ");
		SQL.append("          FROM MUNICIPIO  ");
		SQL.append("          INNER JOIN ENTIDADEOUORGAOAP  ");
		SQL.append("          ON MUNICIPIO.IDCAMARAVEREADORES = ENTIDADEOUORGAOAP.ID  ");
		SQL.append("          INNER JOIN PRESTACAO  ");
		SQL.append("          ON PRESTACAO.IDENTIDADEOUORGAOAP = ENTIDADEOUORGAOAP.ID  ");
		SQL.append("          INNER JOIN REMESSALRF  ");
		SQL.append("          ON REMESSALRF.IDPRESTACAO = PRESTACAO.ID  ");
		SQL.append("          INNER JOIN  ");
		SQL.append("            (SELECT MAX(REMESSALRF.ID) AS IDDAREMESSALRF,  ");
		SQL.append("              REMESSALRF.DTBASE        AS DATABASEREMESSALEG  ");
		SQL.append("            FROM MUNICIPIO  ");
		SQL.append("            INNER JOIN ENTIDADEOUORGAOAP  ");
		SQL.append("            ON MUNICIPIO.IDCAMARAVEREADORES = ENTIDADEOUORGAOAP.ID  ");
		SQL.append("            INNER JOIN PRESTACAO  ");
		SQL.append("            ON PRESTACAO.IDENTIDADEOUORGAOAP = ENTIDADEOUORGAOAP.ID  ");
		SQL.append("            INNER JOIN REMESSALRF  ");
		SQL.append("            ON PRESTACAO.ID = REMESSALRF.IDPRESTACAO  ");
		SQL.append("            INNER JOIN  ");
		SQL.append("              (SELECT MUNICIPIO.NOME AS NOMEMUNICIPIO,  ");
		SQL.append("                REMESSALRF.DTBASE DATABASE,  ");
		SQL.append("                MAX(REMESSALRF.DATAENVIO) AS DATAENVIO1  ");
		SQL.append("              FROM MUNICIPIO  ");
		SQL.append("              INNER JOIN ENTIDADEOUORGAOAP  ");
		SQL.append("              ON MUNICIPIO.IDCAMARAVEREADORES = ENTIDADEOUORGAOAP.ID  ");
		SQL.append("              INNER JOIN PRESTACAO  ");
		SQL.append("              ON PRESTACAO.IDENTIDADEOUORGAOAP = ENTIDADEOUORGAOAP.ID  ");
		SQL.append("              INNER JOIN REMESSALRF  ");
		SQL.append("              ON PRESTACAO.ID          = REMESSALRF.IDPRESTACAO  ");
		SQL.append("              WHERE REMESSALRF.DTBASE IN ('31/12/2002', '31/12/2003', '31/12/2004', '31/12/2005', '31/12/2006', '31/12/2007', '31/12/2008', '31/12/2009', '31/12/2010', '31/12/2011', '31/12/2012', '31/12/2013', '31/12/2014', '31/12/2015', '31/12/2016', '31/12/2017')  ");
		SQL.append("              AND MUNICIPIO.CODIGOIBGE = ").append(codigoIBGE);
		SQL.append("              GROUP BY MUNICIPIO.NOME,  ");
		SQL.append("                REMESSALRF.DTBASE  ");
		SQL.append("              ORDER BY REMESSALRF.DTBASE  ");
		SQL.append("              ) ON DATAENVIO1 = REMESSALRF.DATAENVIO  ");
		SQL.append("            AND DATABASE      = REMESSALRF.DTBASE  ");
		SQL.append("            AND NOMEMUNICIPIO = MUNICIPIO.NOME  ");
		SQL.append("            GROUP BY REMESSALRF.DTBASE,  ");
		SQL.append("              DATAENVIO1  ");
		SQL.append("            ORDER BY REMESSALRF.DTBASE  ");
		SQL.append("            ) ON REMESSALRF.ID = IDDAREMESSALRF  ");
		SQL.append("          )  ");
		SQL.append("        INNER JOIN GESTAOFISCAL  ");
		SQL.append("        ON GESTAOFISCAL.IDPRESTACAOLRF = IDDAPRESTACAO  ");
		SQL.append("        AND GESTAOFISCAL.FOIEXCLUIDA   = 'N'  ");
		SQL.append("        GROUP BY DATABASEREMESSALEG,  ");
		SQL.append("          GESTAOFISCAL.MES  ");
		SQL.append("        ORDER BY DATABASEREMESSALEG,  ");
		SQL.append("          GESTAOFISCAL.MES  ");
		SQL.append("        )  ");
		SQL.append("      INNER JOIN GESTAOFISCAL  ");
		SQL.append("      ON GESTAOFISCAL.ID = IDDAGESTAOFISCAL  ");
		SQL.append("      INNER JOIN DESPESAMENSALPESSOAL  ");
		SQL.append("      ON DESPESAMENSALPESSOAL.ID = GESTAOFISCAL.IDDESPESAMENSALPESSOAL  ");
		SQL.append("      INNER JOIN DESPESAMENSALPESSOALCAM  ");
		SQL.append("      ON DESPESAMENSALPESSOAL.ID = DESPESAMENSALPESSOALCAM.ID  ");
		SQL.append("      ) ON DATABASEREMESSALEG    = DATABASEREMESSA  ");
		SQL.append("    AND MESGESTAO                = MESEXECUCAO  ");
		SQL.append("    GROUP BY NOMEDOMUNICIPIO,  ");
		SQL.append("      DATABASEREMESSA,  ");
		SQL.append("      DATAPUBLICACAO,  ");
		SQL.append("      SITUACAOPUBLICACAO,  ");
		SQL.append("      OPCAOSEMESTRALIDADE,  ");
		SQL.append("      IDDAPRESTACAO  ");
		SQL.append("    ORDER BY DATABASEREMESSA  ");
		SQL.append("    )  ");
		SQL.append("  INNER JOIN PRESTACAO  ");
		SQL.append("  ON PRESTACAO.ID = IDDAPRESTACAO  ");
		SQL.append("  INNER JOIN EXECUCAOORCAMENTARIA  ");
		SQL.append("  ON EXECUCAOORCAMENTARIA.IDPRESTACAOLRFEXECUTIVO = IDDAPRESTACAO  ");
		SQL.append("  AND EXECUCAOORCAMENTARIA.MES                    = 1  ");
		SQL.append("  GROUP BY NOMEDOMUNICIPIO,  ");
		SQL.append("    DATABASEREMESSA,  ");
		SQL.append("    RCLEXECUTIVO,  ");
		SQL.append("    OPERACOESCREDITOPREVINICIAL,  ");
		SQL.append("    DATAPUBLICACAO,  ");
		SQL.append("    SITUACAOPUBLICACAO,  ");
		SQL.append("    OPCAOSEMESTRALIDADE,  ");
		SQL.append("    DESPESATOTALPESSOALEXECUTIVO,  ");
		SQL.append("    DESPESATOTALPESSOALLEG  ");
		SQL.append("  )  ");
		SQL.append("INNER JOIN EXECUCAOBIMESTRAL  ");
		SQL.append("ON IDDAEXECUCAOORCAMENTARIA       = EXECUCAOBIMESTRAL.IDEXECUCAOORCAMENTARIA  ");
		SQL.append("AND EXECUCAOBIMESTRAL.FOIEXCLUIDO = 'N'  ");
		SQL.append("INNER JOIN EXECUCAODESPESA  ");
		SQL.append("ON EXECUCAODESPESA.ID = EXECUCAOBIMESTRAL.IDEXECUCAODESPESA  ");
		SQL.append("INNER JOIN DESPESACAPITAL  ");
		SQL.append("ON DESPESACAPITAL.IDEXECUCAODESPESA = EXECUCAODESPESA.ID  ");
		SQL.append("AND DESPESACAPITAL.TIPODESPESA      = 1  ");
		SQL.append("ORDER BY DATABASEREMESSA");
		SQL.append(" ) a where EXTRACT(YEAR FROM a.databaseremessa )  >= ").append(ultimoExercicioParecerPrevio);
		
		return SQL.toString();
	}
	
private StringBuilder getSQLRelatorioSIACE(String numAno, String dtBase, String codigoIBGE) {
		
		StringBuilder sqlSIACE = new StringBuilder();
		sqlSIACE.append("SELECT NOMEMUNICIPIO, ");
		sqlSIACE.append("  DATAPUBLICACAO, ");
		sqlSIACE.append("  OPTANTE, ");
		sqlSIACE.append("  ROUND((DESPESATOTALPESSOALPREF  /RECEITACORRENTELIQPREF*100),2)                                                    AS PORCENTDESPTOTPESSOALEXEC, ");
		sqlSIACE.append("  ROUND((DESPESATOTALPESSOALPL    /RECEITACORRENTELIQPL*100),2)                                                      AS PORCENTDESPTOTPESSOALPL, ");
		sqlSIACE.append("  ROUND((DESPESATOTALPESSOALPL    /RECEITACORRENTELIQPL*100)+(DESPESATOTALPESSOALPREF/RECEITACORRENTELIQPREF*100),2) AS PORCENTTOTALDESPTOTPESSOAL, ");
		sqlSIACE.append("  ROUND((DIVIDACONSOLIDADALIQUIDA /RECEITACORRENTELIQPREF*100),2)                                                    AS DIVIDACONSOLIDADALIQEXEC, ");
		sqlSIACE.append("  ROUND((ARO                      /RECEITACORRENTELIQPREF*100),2)                                                    AS AROEXEC, ");
		sqlSIACE.append("  ROUND(DEMONSTRATIVOOPCREDITOEXEC/RECEITACORRENTELIQPREF*100,2)                                                     AS OPERACOESCREDITOEXEC, ");
		sqlSIACE.append("  ROUND(CONCESSAOGARANTIA         /RECEITACORRENTELIQPREF*100,2)                                                     AS CONCESSAOGARANTIAEXEC, ");
		sqlSIACE.append("  ( ");
		sqlSIACE.append("  CASE ");
		sqlSIACE.append("    WHEN (DISPFINANCEIRAPE+DISPFINANCEIRAPL) < (VALORPROCENAOPROCPE+VALORPROCENAOPROCPL) ");
		sqlSIACE.append("    THEN 'Ultrapassou' ");
		sqlSIACE.append("    ELSE 'Não ultrapassou' ");
		sqlSIACE.append("  END )                                                         AS DISPFINACxINSCRESTPAGAR, ");
		sqlSIACE.append("  ROUND(OPERACOESCREDITOEXERCICIO/RECEITACORRENTELIQPREF*100,2) AS PORCOPERACOESCREDITO, ");
		sqlSIACE.append("  IPTUPREVISTA, ");
		sqlSIACE.append("  IPTUREALIZADA, ");
		sqlSIACE.append("  ISSQNPREVISTA, ");
		sqlSIACE.append("  ISSQNREALIZADA, ");
		sqlSIACE.append("  ITBIPREVISTA, ");
		sqlSIACE.append("  ITBIREALIZADA, ");
		sqlSIACE.append("  IRRFPREVISTA, ");
		sqlSIACE.append("  IRRFREALIZADA, ");
		sqlSIACE.append("  DIVIDACONSOLIDADA ");
		sqlSIACE.append("FROM ");
		sqlSIACE.append("  (SELECT NOMEMUNICIPIO, ");
		sqlSIACE.append("    DATARECEBIMENTO, ");
		sqlSIACE.append("    DATAPUBLICACAO, ");
		sqlSIACE.append("    SUM(VALORIPTU)                     AS IPTUREALIZADA, ");
		sqlSIACE.append("    SUM(VALORISSQN)                    AS ISSQNREALIZADA, ");
		sqlSIACE.append("    SUM(VALORITBI)                     AS ITBIREALIZADA, ");
		sqlSIACE.append("    SUM(VALORIRRF)                     AS IRRFREALIZADA, ");
		sqlSIACE.append("    SUM(DESPESAMENSALTOTALPESSOALPREF) AS DESPESATOTALPESSOALPREF, ");
		sqlSIACE.append("    SUM(RECEITACORRENTELIQMENSALPREF)  AS RECEITACORRENTELIQPREF, ");
		sqlSIACE.append("    SUM(OPERACOESCREDEXERCICIOMENSAL)  AS OPERACOESCREDITOEXERCICIO, ");
		sqlSIACE.append("    ARO, ");
		sqlSIACE.append("    DEMONSTRATIVOOPCREDITOEXEC, ");
		sqlSIACE.append("    CONCESSAOGARANTIA, ");
		sqlSIACE.append("    DIVIDACONSOLIDADA, ");
		sqlSIACE.append("    ( ");
		sqlSIACE.append("    CASE ");
		sqlSIACE.append("      WHEN (RESTOAPAGAR-SALDOPRECATORIO+INSCRICOESRESTOAPAGAR>SUBTRACAORESULTADONOMINAL) ");
		sqlSIACE.append("      THEN DIVIDACONSOLIDADA ");
		sqlSIACE.append("      ELSE (DIVIDACONSOLIDADA-SUBTRACAORESULTADONOMINAL+RESTOAPAGAR-SALDOPRECATORIO+INSCRICOESRESTOAPAGAR) ");
		sqlSIACE.append("    END) AS DIVIDACONSOLIDADALIQUIDA ");
		sqlSIACE.append("  FROM ");
		sqlSIACE.append("    (SELECT DISTINCT NOMEMUNICIPIO, ");
		sqlSIACE.append("      MESEXECUCAOORCAMENTARIA, ");
		sqlSIACE.append("      DATARECEBIMENTO, ");
		sqlSIACE.append("      DATAPUBLICACAO, ");
		sqlSIACE.append("      RECEITAIMPOSTOS.VALORIPTU  AS VALORIPTU, ");
		sqlSIACE.append("      RECEITAIMPOSTOS.VALORIRRF  AS VALORIRRF, ");
		sqlSIACE.append("      RECEITAIMPOSTOS.VALORISSQN AS VALORISSQN, ");
		sqlSIACE.append("      RECEITAIMPOSTOS.VALORITBI  AS VALORITBI, ");
		sqlSIACE.append("      (RECEITATRIBUTARIA.RECEITACONTMELHORIA     +RECEITATRIBUTARIA.RECEITATAXAS +RECEITAIMPOSTOS.VALORITBI +RECEITAIMPOSTOS.VALORISSQN +RECEITAIMPOSTOS.VALORIRRF +RECEITAIMPOSTOS.VALORIPTU +RECEITACORRENTE.RECEITACONTRIBUICOES +RECEITAPATRIMONIAL.RECEITAAPLICACOES +RECEITAPATRIMONIAL.VALOROUTRASRECEITAS +RECEITACORRENTE.RECEITAINDUSTRIAIS +RECEITACORRENTE.RECEITAAGROPECUARIAS +RECEITACORRENTE.RECEITASERVICOS +TRANSFERENCIACORRENTE.COTAPARTEFPM +TRANSFERENCIACORRENTE.COTAPARTEICMS +TRANSFERENCIACORRENTE.COTAPARTEIPVA +TRANSFERENCIACORRENTE.COTAPARTEIPI +TRANSFERENCIACORRENTE.TRANSFERENCIAFUNDEF +TRANSFERENCIACORRENTE.OUTRASTRANSFERENCIAS +TRANSFERENCIACORRENTE.CONVENIOS +RECEITACORRENTE.OUTRASRECEITASCORRENTES -EXCLUSAORECEITA.CONTSERVPREVPROP -EXCLUSAORECEITA.COMPENSREGPREV -EXCLUSAORECEITA.OUTRASDUPLICIDADES -EXCLUSAORECEITA.CONTPATRONALPREVPROP -TRANSFINTRAGOVERNAMENTAL.TRANSFFUNDACOES -TRANSFINTRAGOVERNAMENTAL.TRANSFAUTARQUIAS -TRANSFINTRAGOVERNAMENTAL.TRANSFEMPESTDEP - ");
		sqlSIACE.append("      TRANSFINTRAGOVERNAMENTAL.TRANSFDEMAISENT   -DEDUCAORECEITA.DEDUCAOFUNDEF -RECEITACORRENTE.DEDUCOESRECEITACORRENTE )                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             AS RECEITACORRENTELIQMENSALPREF, ");
		sqlSIACE.append("      (DESPESAMENSALPESSOAL.VENCIMENTOSVANTAGENS +DESPESAMENSALPESSOAL.INATIVOS +DESPESAMENSALPESSOAL.PENSIONISTAS +DESPESAMENSALPESSOAL.SALARIOFAMILIA +DESPESAMENSALPESSOALPREF.SUBSIDIOPREFEITO +DESPESAMENSALPESSOALPREF.SUBSIDIOVICEPREFEITO +DESPESAMENSALPESSOALPREF.SUBSIDIOSECRETARIOSMUNICIPAIS +DESPESAMENSALPESSOAL.OBRIGACOESPATRONAIS +DESPESAMENSALPESSOAL.REPASSEPATRONAL +DESPESAMENSALPESSOAL.SENTENCASJUDICIARIAS +DESPESAMENSALPESSOAL.OUTRASDESPESASPESSOAL +DESPESAMENSALPESSOAL.DESPESASANTERIORES +DESPESAMENSALPESSOAL.DESPESASANTCORRESPONDENTE +DESPESAMENSALPESSOAL.DESPESASANTERIORESCOMPETENCIA -DESPESAMENSALPESSOAL.INATIVOS -DESPESAMENSALPESSOAL.PENSIONISTAS -DESPESAMENSALPESSOAL.INDENIZACOESDEMISSAO -DESPESAMENSALPESSOAL.INCENTIVOSDEMISSAOVOLUNTARIA -DESPESAMENSALPESSOAL.SENTENCASJUDICIARIASANTERIORES -DESPESAMENSALPESSOAL.DESPESASANTCORRESPONDENTE -DESPESAMENSALPESSOAL.DESPESASANTERIORESEXCLUSAO ) AS DESPESAMENSALTOTALPESSOALPREF, ");
		sqlSIACE.append("      OPERACOESCREDITO.RECEITAOUTRASOPCREDITO                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         AS OPERACOESCREDEXERCICIOMENSAL ");
		sqlSIACE.append("    FROM RECEITAIMPOSTOS ");
		sqlSIACE.append("    INNER JOIN RECEITATRIBUTARIA ");
		sqlSIACE.append("    ON RECEITATRIBUTARIA.IDRECEITAIMPOSTOS = RECEITAIMPOSTOS.ID ");
		sqlSIACE.append("    INNER JOIN RECEITACORRENTE ");
		sqlSIACE.append("    ON RECEITACORRENTE.IDRECEITATRIBUTARIA = RECEITATRIBUTARIA.ID ");
		sqlSIACE.append("    INNER JOIN EXECUCAORECEITA ");
		sqlSIACE.append("    ON EXECUCAORECEITA.ID = RECEITACORRENTE.IDEXECUCAORECEITA ");
		sqlSIACE.append("    INNER JOIN RECEITAPATRIMONIAL ");
		sqlSIACE.append("    ON RECEITAPATRIMONIAL.ID = RECEITACORRENTE.IDRECEITAPATRIMONIAL ");
		sqlSIACE.append("    INNER JOIN TRANSFERENCIACORRENTE ");
		sqlSIACE.append("    ON TRANSFERENCIACORRENTE.ID = RECEITACORRENTE.IDTRANSFERENCIACORRENTE ");
		sqlSIACE.append("    INNER JOIN EXCLUSAORECEITA ");
		sqlSIACE.append("    ON EXCLUSAORECEITA.ID = EXECUCAORECEITA.IDEXCLUSAORECEITA ");
		sqlSIACE.append("    INNER JOIN TRANSFINTRAGOVERNAMENTAL ");
		sqlSIACE.append("    ON TRANSFINTRAGOVERNAMENTAL.ID = EXCLUSAORECEITA.IDEXCLUSAORECTRANSFCORRENTE ");
		sqlSIACE.append("    INNER JOIN DEDUCAORECEITA ");
		sqlSIACE.append("    ON DEDUCAORECEITA.IDEXECUCAORECEITA = EXECUCAORECEITA.ID ");
		sqlSIACE.append("    INNER JOIN RECEITACAPITAL ");
		sqlSIACE.append("    ON RECEITACAPITAL.IDEXECUCAORECEITA = EXECUCAORECEITA.ID ");
		sqlSIACE.append("    INNER JOIN OPERACOESCREDITO ");
		sqlSIACE.append("    ON OPERACOESCREDITO.ID = RECEITACAPITAL.IDOPERACOESCREDITO, ");
		sqlSIACE.append("      (SELECT MAX(EXECUCAOBIMESTRAL.IDEXECUCAORECEITA) IDDAEXECUCAORECEITA, ");
		sqlSIACE.append("        MAX(EXECUCAOBISEMESTRAL.IDRESULTADONOMINAL) IDDORESULTADONOMINAL, ");
		sqlSIACE.append("        NOMEMUNICIPIO, ");
		sqlSIACE.append("        MESEXECUCAOORCAMENTARIA, ");
		sqlSIACE.append("        DATARECEBIMENTO, ");
		sqlSIACE.append("        DATAPUBLICACAO, ");
		sqlSIACE.append("        IDDAPRESTACAO ");
		sqlSIACE.append("      FROM EXECUCAOBIMESTRAL, ");
		sqlSIACE.append("        EXECUCAOBISEMESTRAL, ");
		sqlSIACE.append("        (SELECT DISTINCT EXECUCAOORCAMENTARIA.ID AS IDDAEXECUCAOORCAMENTARIA, ");
		sqlSIACE.append("          EXECUCAOORCAMENTARIA.MES               AS MESEXECUCAOORCAMENTARIA, ");
		sqlSIACE.append("          MUNICIPIO.NOME                         AS NOMEMUNICIPIO, ");
		sqlSIACE.append("          DATARECEBIMENTO, ");
		sqlSIACE.append("          DATAPUBLICACAO, ");
		sqlSIACE.append("          IDDAPRESTACAO ");
		sqlSIACE.append("        FROM MUNICIPIO ");
		sqlSIACE.append("        INNER JOIN ENTIDADEOUORGAOAP ");
		sqlSIACE.append("        ON MUNICIPIO.IDPREFEITURA = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("        INNER JOIN PRESTACAO ");
		sqlSIACE.append("        ON PRESTACAO.IDENTIDADEOUORGAOAP = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("        INNER JOIN EXECUCAOORCAMENTARIA ");
		sqlSIACE.append("        ON PRESTACAO.ID = EXECUCAOORCAMENTARIA.IDPRESTACAOLRFEXECUTIVO, ");
		sqlSIACE.append("          (SELECT PRESTACAO.ID IDDAPRESTACAO, ");
		sqlSIACE.append("            MAX(REMESSALRF.DATAENVIO)      AS DATARECEBIMENTO, ");
		sqlSIACE.append("            MAX(REMESSALRF.DATAPUBLICACAO) AS DATAPUBLICACAO ");
		sqlSIACE.append("          FROM MUNICIPIO ");
		sqlSIACE.append("          INNER JOIN ENTIDADEOUORGAOAP ");
		sqlSIACE.append("          ON MUNICIPIO.IDPREFEITURA = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("          INNER JOIN PRESTACAO ");
		sqlSIACE.append("          ON PRESTACAO.IDENTIDADEOUORGAOAP = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("          INNER JOIN REMESSALRF ");
		sqlSIACE.append("          ON PRESTACAO.ID = REMESSALRF.IDPRESTACAO, ");
		sqlSIACE.append("            DATALIMITE ");
		sqlSIACE.append("          WHERE REMESSALRF.DTBASE = ").append(dtBase);
		sqlSIACE.append("             ");
		sqlSIACE.append("          AND REMESSALRF.DTBASE = DATALIMITE.DTBASE ");
		sqlSIACE.append("          AND MUNICIPIO.CODIGOIBGE = ").append(codigoIBGE);
		sqlSIACE.append("             ");
		sqlSIACE.append("          GROUP BY PRESTACAO.ID ");
		sqlSIACE.append("          ) ");
		sqlSIACE.append("        WHERE IDDAPRESTACAO = PRESTACAO.ID ");
		sqlSIACE.append("        AND PRESTACAO.EXERCICIO =  ").append(numAno);
		sqlSIACE.append("        ORDER BY EXECUCAOORCAMENTARIA.MES ");
		sqlSIACE.append("        ) ");
		sqlSIACE.append("      WHERE IDDAEXECUCAOORCAMENTARIA = EXECUCAOBIMESTRAL.IDEXECUCAOORCAMENTARIA ");
		sqlSIACE.append("      AND IDDAEXECUCAOORCAMENTARIA   = EXECUCAOBISEMESTRAL.IDEXECUCAOORCAMENTARIA ");
		sqlSIACE.append("      GROUP BY NOMEMUNICIPIO, ");
		sqlSIACE.append("        MESEXECUCAOORCAMENTARIA, ");
		sqlSIACE.append("        DATARECEBIMENTO, ");
		sqlSIACE.append("        DATAPUBLICACAO, ");
		sqlSIACE.append("        IDDAPRESTACAO ");
		sqlSIACE.append("      ORDER BY MESEXECUCAOORCAMENTARIA ");
		sqlSIACE.append("      ), ");
		sqlSIACE.append("      GESTAOFISCAL ");
		sqlSIACE.append("    INNER JOIN DESPESAMENSALPESSOAL ");
		sqlSIACE.append("    ON GESTAOFISCAL.IDDESPESAMENSALPESSOAL = DESPESAMENSALPESSOAL.ID ");
		sqlSIACE.append("    INNER JOIN DESPESAMENSALPESSOALPREF ");
		sqlSIACE.append("    ON DESPESAMENSALPESSOALPREF.ID  = DESPESAMENSALPESSOAL.ID ");
		sqlSIACE.append("    WHERE EXECUCAORECEITA.ID        = IDDAEXECUCAORECEITA ");
		sqlSIACE.append("    AND GESTAOFISCAL.IDPRESTACAOLRF = IDDAPRESTACAO ");
		sqlSIACE.append("    AND GESTAOFISCAL.MES            =MESEXECUCAOORCAMENTARIA ");
		sqlSIACE.append("    AND RECEITACORRENTE.TIPORECEITA = 4 ");
		sqlSIACE.append("    AND DEDUCAORECEITA.TIPORECEITA  = 4 ");
		sqlSIACE.append("    AND RECEITACAPITAL.TIPORECEITA  = 4 ");
		sqlSIACE.append("    ORDER BY MESEXECUCAOORCAMENTARIA ");
		sqlSIACE.append("    ), ");
		sqlSIACE.append("    (SELECT DISTINCT RESTOAPAGARPREF+RESTOAPAGARCAM+RESTOAPAGARENT-RESTOAPAGARIPP-RESULTADONOMINAL.SALDOPRECATORIOS AS RESTOAPAGAR, ");
		sqlSIACE.append("      RESULTADONOMINAL.DIVIDACONSOLIDADA DIVIDACONSOLIDADA, ");
		sqlSIACE.append("      (RESULTADONOMINAL.DISPONIBILIDADECAIXA +RESULTADONOMINAL.APLICACAOFINANCEIRA +RESULTADONOMINAL.ATIVOFINANCEIRO )                                                                                                                                                                                                                                                                                                                                                                AS SUBTRACAORESULTADONOMINAL, ");
		sqlSIACE.append("      RESULTADONOMINAL.SALDOPRECATORIOS                                                                                                                                                                                                                                                                                                                                                                                                                                               AS SALDOPRECATORIO, ");
		sqlSIACE.append("      (INSCRICAORESTOSAPAGAR.VALORPROCESSADO +INSCRICAORESTOSAPAGAR.VALORPROCESSADOLEGISLATIVO +INSCRICAORESTOSAPAGAR.VALORPROCESSADORPPSAS)                                                                                                                                                                                                                                                                                                                                          AS INSCRICOESRESTOAPAGAR, ");
		sqlSIACE.append("      ITEMCOMPARATIVOPE.ANTECIPACAORECEITAORCAMENTARIA                                                                                                                                                                                                                                                                                                                                                                                                                                AS ARO, ");
		sqlSIACE.append("      (DEMONSTRATIVOOPCREDITO.MOBILIARIAINTERNA +DEMONSTRATIVOOPCREDITO.MOBILIARIAEXTERNA +DEMONSTRATIVOOPCREDITO.CONTRATUALEXTERNA +DEMONSTRATIVOOPCREDITO.ABERTURACREDITO +DEMONSTRATIVOOPCREDITO.DERIVADASPPP +DEMONSTRATIVOOPCREDITO.DEMAISAQUISFINANC +DEMONSTRATIVOOPCREDITO.PELAVENDATERMOBS +DEMONSTRATIVOOPCREDITO.DEMAISANTECIPRECEITA +DEMONSTRATIVOOPCREDITO.ASSUNCAORECCONFDIV +DEMONSTRATIVOOPCREDITO.OUTRASOPERACOESCREDITO +DEMONSTRATIVOOPCREDITO.OPERACOESVEDADAS ) AS DEMONSTRATIVOOPCREDITOEXEC, ");
		sqlSIACE.append("      ITEMCOMPARATIVOPE.CONCESSAOGARANTIA                                                                                                                                                                                                                                                                                                                                                                                                                                             AS CONCESSAOGARANTIA, ");
		sqlSIACE.append("      MESEXECUCAOORCAMENTARIA1 ");
		sqlSIACE.append("    FROM RESULTADONOMINAL, ");
		sqlSIACE.append("      GESTAOFISCAL ");
		sqlSIACE.append("    INNER JOIN INSCRICAORESTOSAPAGAR ");
		sqlSIACE.append("    ON GESTAOFISCAL.IDINSCRICAORESTOSAPAGAR = INSCRICAORESTOSAPAGAR.ID ");
		sqlSIACE.append("    INNER JOIN ITEMCOMPARATIVOPE ");
		sqlSIACE.append("    ON ITEMCOMPARATIVOPE.ID = GESTAOFISCAL.IDITEMCOMPARATIVO ");
		sqlSIACE.append("    INNER JOIN DEMONSTRATIVOOPCREDITO ");
		sqlSIACE.append("    ON DEMONSTRATIVOOPCREDITO.ID = GESTAOFISCAL.IDDEMONSTRATIVOOPCREDITO, ");
		sqlSIACE.append("      (SELECT MAX(EXECUCAOBISEMESTRAL.IDEXECUCAORESTOSAPAGAR) IDDAEXECUCAORESTOSAPAGAR, ");
		sqlSIACE.append("        MAX(EXECUCAOBISEMESTRAL.IDRESULTADONOMINAL) IDDORESULTADONOMINAL, ");
		sqlSIACE.append("        MESEXECUCAOORCAMENTARIA1, ");
		sqlSIACE.append("        IDDAPRESTACAO ");
		sqlSIACE.append("      FROM EXECUCAOBISEMESTRAL, ");
		sqlSIACE.append("        (SELECT DISTINCT EXECUCAOORCAMENTARIA.ID AS IDDAEXECUCAOORCAMENTARIA, ");
		sqlSIACE.append("          EXECUCAOORCAMENTARIA.MES               AS MESEXECUCAOORCAMENTARIA1, ");
		sqlSIACE.append("          MUNICIPIO.NOME                         AS NOMEMUNICIPIO, ");
		sqlSIACE.append("          IDDAPRESTACAO ");
		sqlSIACE.append("        FROM MUNICIPIO ");
		sqlSIACE.append("        INNER JOIN ENTIDADEOUORGAOAP ");
		sqlSIACE.append("        ON MUNICIPIO.IDPREFEITURA = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("        INNER JOIN PRESTACAO ");
		sqlSIACE.append("        ON PRESTACAO.IDENTIDADEOUORGAOAP = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("        INNER JOIN EXECUCAOORCAMENTARIA ");
		sqlSIACE.append("        ON PRESTACAO.ID = EXECUCAOORCAMENTARIA.IDPRESTACAOLRFEXECUTIVO, ");
		sqlSIACE.append("          (SELECT PRESTACAO.ID IDDAPRESTACAO, ");
		sqlSIACE.append("            MAX(REMESSALRF.DATAENVIO) AS DATARECEBIMENTO ");
		sqlSIACE.append("          FROM MUNICIPIO ");
		sqlSIACE.append("          INNER JOIN ENTIDADEOUORGAOAP ");
		sqlSIACE.append("          ON MUNICIPIO.IDPREFEITURA = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("          INNER JOIN PRESTACAO ");
		sqlSIACE.append("          ON PRESTACAO.IDENTIDADEOUORGAOAP = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("          INNER JOIN REMESSALRF ");
		sqlSIACE.append("          ON PRESTACAO.ID = REMESSALRF.IDPRESTACAO, ");
		sqlSIACE.append("            DATALIMITE ");
		sqlSIACE.append("          WHERE REMESSALRF.DTBASE = ").append(dtBase);
		sqlSIACE.append("             ");
		sqlSIACE.append("          AND REMESSALRF.DTBASE = DATALIMITE.DTBASE ");
		sqlSIACE.append("          AND MUNICIPIO.CODIGOIBGE = ").append(codigoIBGE);
		sqlSIACE.append("             ");
		sqlSIACE.append("          GROUP BY PRESTACAO.ID ");
		sqlSIACE.append("          ) ");
		sqlSIACE.append("        WHERE IDDAPRESTACAO = PRESTACAO.ID ");
		sqlSIACE.append("        AND PRESTACAO.EXERCICIO      = ").append(numAno);
		sqlSIACE.append("        AND EXECUCAOORCAMENTARIA.MES = 12 ");
		sqlSIACE.append("        ORDER BY EXECUCAOORCAMENTARIA.MES ");
		sqlSIACE.append("        ) ");
		sqlSIACE.append("      WHERE IDDAEXECUCAOORCAMENTARIA = EXECUCAOBISEMESTRAL.IDEXECUCAOORCAMENTARIA ");
		sqlSIACE.append("      GROUP BY MESEXECUCAOORCAMENTARIA1, ");
		sqlSIACE.append("        IDDAPRESTACAO ");
		sqlSIACE.append("      ORDER BY MESEXECUCAOORCAMENTARIA1 ");
		sqlSIACE.append("      ), ");
		sqlSIACE.append("      (SELECT ( ");
		sqlSIACE.append("        CASE ");
		sqlSIACE.append("          WHEN SUM(ITEMRESTOAPAGAR.VALORINSCRITO-ITEMRESTOAPAGAR.VALORCANCELADO-ITEMRESTOAPAGAR.VALORPAGO) IS NULL ");
		sqlSIACE.append("          THEN 0.0 ");
		sqlSIACE.append("          ELSE SUM(ITEMRESTOAPAGAR.VALORINSCRITO-ITEMRESTOAPAGAR.VALORCANCELADO-ITEMRESTOAPAGAR.VALORPAGO) ");
		sqlSIACE.append("        END ) AS RESTOAPAGARPREF ");
		sqlSIACE.append("      FROM EXECUCAORESTOSAPAGAR ");
		sqlSIACE.append("      INNER JOIN RESTOAPAGARANTERIOR ");
		sqlSIACE.append("      ON RESTOAPAGARANTERIOR.IDEXECUCAORESTOSAPAGAR = EXECUCAORESTOSAPAGAR.ID ");
		sqlSIACE.append("      INNER JOIN ITEMRESTOAPAGAR ");
		sqlSIACE.append("      ON RESTOAPAGARANTERIOR.IDITEMRESTOAPAGARPROCESSADO = ITEMRESTOAPAGAR.ID, ");
		sqlSIACE.append("        (SELECT MAX(EXECUCAOBISEMESTRAL.IDEXECUCAORESTOSAPAGAR) IDDAEXECUCAORESTOSAPAGAR, ");
		sqlSIACE.append("          MESEXECUCAOORCAMENTARIA1, ");
		sqlSIACE.append("          IDDAPRESTACAO ");
		sqlSIACE.append("        FROM EXECUCAOBISEMESTRAL, ");
		sqlSIACE.append("          (SELECT DISTINCT EXECUCAOORCAMENTARIA.ID AS IDDAEXECUCAOORCAMENTARIA, ");
		sqlSIACE.append("            EXECUCAOORCAMENTARIA.MES               AS MESEXECUCAOORCAMENTARIA1, ");
		sqlSIACE.append("            MUNICIPIO.NOME                         AS NOMEMUNICIPIO, ");
		sqlSIACE.append("            IDDAPRESTACAO ");
		sqlSIACE.append("          FROM MUNICIPIO ");
		sqlSIACE.append("          INNER JOIN ENTIDADEOUORGAOAP ");
		sqlSIACE.append("          ON MUNICIPIO.IDPREFEITURA = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("          INNER JOIN PRESTACAO ");
		sqlSIACE.append("          ON PRESTACAO.IDENTIDADEOUORGAOAP = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("          INNER JOIN EXECUCAOORCAMENTARIA ");
		sqlSIACE.append("          ON PRESTACAO.ID = EXECUCAOORCAMENTARIA.IDPRESTACAOLRFEXECUTIVO, ");
		sqlSIACE.append("            (SELECT PRESTACAO.ID IDDAPRESTACAO, ");
		sqlSIACE.append("              MAX(REMESSALRF.DATAENVIO)      AS DATARECEBIMENTO, ");
		sqlSIACE.append("              MAX(REMESSALRF.DATAPUBLICACAO) AS DATAPUBLICACAO ");
		sqlSIACE.append("            FROM MUNICIPIO ");
		sqlSIACE.append("            INNER JOIN ENTIDADEOUORGAOAP ");
		sqlSIACE.append("            ON MUNICIPIO.IDPREFEITURA = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("            INNER JOIN PRESTACAO ");
		sqlSIACE.append("            ON PRESTACAO.IDENTIDADEOUORGAOAP = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("            INNER JOIN REMESSALRF ");
		sqlSIACE.append("            ON PRESTACAO.ID = REMESSALRF.IDPRESTACAO, ");
		sqlSIACE.append("              DATALIMITE ");
		sqlSIACE.append("            WHERE REMESSALRF.DTBASE = ").append(dtBase);
		sqlSIACE.append("               ");
		sqlSIACE.append("            AND REMESSALRF.DTBASE = DATALIMITE.DTBASE ");
		sqlSIACE.append("            AND MUNICIPIO.CODIGOIBGE = ").append(codigoIBGE);
		sqlSIACE.append("               ");
		sqlSIACE.append("            GROUP BY PRESTACAO.ID ");
		sqlSIACE.append("            ) ");
		sqlSIACE.append("          WHERE IDDAPRESTACAO = PRESTACAO.ID ");
		sqlSIACE.append("          AND PRESTACAO.EXERCICIO      =  ").append(numAno);
		sqlSIACE.append("          AND EXECUCAOORCAMENTARIA.MES = 12 ");
		sqlSIACE.append("          ORDER BY EXECUCAOORCAMENTARIA.MES ");
		sqlSIACE.append("          ) ");
		sqlSIACE.append("        WHERE IDDAEXECUCAOORCAMENTARIA = EXECUCAOBISEMESTRAL.IDEXECUCAOORCAMENTARIA ");
		sqlSIACE.append("        GROUP BY MESEXECUCAOORCAMENTARIA1, ");
		sqlSIACE.append("          IDDAPRESTACAO ");
		sqlSIACE.append("        ORDER BY MESEXECUCAOORCAMENTARIA1 ");
		sqlSIACE.append("        ) ");
		sqlSIACE.append("      WHERE IDDAEXECUCAORESTOSAPAGAR     = EXECUCAORESTOSAPAGAR.ID ");
		sqlSIACE.append("      AND RESTOAPAGARANTERIOR.VINCULADOA = 1 ");
		sqlSIACE.append("      ), ");
		sqlSIACE.append("      (SELECT ( ");
		sqlSIACE.append("        CASE ");
		sqlSIACE.append("          WHEN SUM(ITEMRESTOAPAGAR.VALORINSCRITO-ITEMRESTOAPAGAR.VALORCANCELADO-ITEMRESTOAPAGAR.VALORPAGO) IS NULL ");
		sqlSIACE.append("          THEN 0.0 ");
		sqlSIACE.append("          ELSE SUM(ITEMRESTOAPAGAR.VALORINSCRITO-ITEMRESTOAPAGAR.VALORCANCELADO-ITEMRESTOAPAGAR.VALORPAGO) ");
		sqlSIACE.append("        END ) AS RESTOAPAGARENT ");
		sqlSIACE.append("      FROM EXECUCAORESTOSAPAGAR ");
		sqlSIACE.append("      INNER JOIN RESTOAPAGARANTERIOR ");
		sqlSIACE.append("      ON RESTOAPAGARANTERIOR.IDEXECUCAORESTOSAPAGAR = EXECUCAORESTOSAPAGAR.ID ");
		sqlSIACE.append("      INNER JOIN ITEMRESTOAPAGAR ");
		sqlSIACE.append("      ON RESTOAPAGARANTERIOR.IDITEMRESTOAPAGARPROCESSADO = ITEMRESTOAPAGAR.ID, ");
		sqlSIACE.append("        (SELECT MAX(EXECUCAOBISEMESTRAL.IDEXECUCAORESTOSAPAGAR) IDDAEXECUCAORESTOSAPAGAR, ");
		sqlSIACE.append("          MESEXECUCAOORCAMENTARIA1, ");
		sqlSIACE.append("          IDDAPRESTACAO ");
		sqlSIACE.append("        FROM EXECUCAOBISEMESTRAL, ");
		sqlSIACE.append("          (SELECT DISTINCT EXECUCAOORCAMENTARIA.ID AS IDDAEXECUCAOORCAMENTARIA, ");
		sqlSIACE.append("            EXECUCAOORCAMENTARIA.MES               AS MESEXECUCAOORCAMENTARIA1, ");
		sqlSIACE.append("            MUNICIPIO.NOME                         AS NOMEMUNICIPIO, ");
		sqlSIACE.append("            IDDAPRESTACAO ");
		sqlSIACE.append("          FROM MUNICIPIO ");
		sqlSIACE.append("          INNER JOIN ENTIDADEOUORGAOAP ");
		sqlSIACE.append("          ON MUNICIPIO.IDPREFEITURA = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("          INNER JOIN PRESTACAO ");
		sqlSIACE.append("          ON PRESTACAO.IDENTIDADEOUORGAOAP = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("          INNER JOIN EXECUCAOORCAMENTARIA ");
		sqlSIACE.append("          ON PRESTACAO.ID = EXECUCAOORCAMENTARIA.IDPRESTACAOLRFEXECUTIVO, ");
		sqlSIACE.append("            (SELECT PRESTACAO.ID IDDAPRESTACAO, ");
		sqlSIACE.append("              MAX(REMESSALRF.DATAENVIO)      AS DATARECEBIMENTO, ");
		sqlSIACE.append("              MAX(REMESSALRF.DATAPUBLICACAO) AS DATAPUBLICACAO ");
		sqlSIACE.append("            FROM MUNICIPIO ");
		sqlSIACE.append("            INNER JOIN ENTIDADEOUORGAOAP ");
		sqlSIACE.append("            ON MUNICIPIO.IDPREFEITURA = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("            INNER JOIN PRESTACAO ");
		sqlSIACE.append("            ON PRESTACAO.IDENTIDADEOUORGAOAP = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("            INNER JOIN REMESSALRF ");
		sqlSIACE.append("            ON PRESTACAO.ID = REMESSALRF.IDPRESTACAO, ");
		sqlSIACE.append("              DATALIMITE ");
		sqlSIACE.append("            WHERE REMESSALRF.DTBASE = ").append(dtBase);
		sqlSIACE.append("               ");
		sqlSIACE.append("            AND REMESSALRF.DTBASE = DATALIMITE.DTBASE ");
		sqlSIACE.append("            AND MUNICIPIO.CODIGOIBGE = ").append(codigoIBGE);
		sqlSIACE.append("               ");
		sqlSIACE.append("            GROUP BY PRESTACAO.ID ");
		sqlSIACE.append("            ) ");
		sqlSIACE.append("          WHERE IDDAPRESTACAO = PRESTACAO.ID ");
		sqlSIACE.append("          AND PRESTACAO.EXERCICIO      =  ").append(numAno);
		sqlSIACE.append("          AND EXECUCAOORCAMENTARIA.MES = 12 ");
		sqlSIACE.append("          ORDER BY EXECUCAOORCAMENTARIA.MES ");
		sqlSIACE.append("          ) ");
		sqlSIACE.append("        WHERE IDDAEXECUCAOORCAMENTARIA = EXECUCAOBISEMESTRAL.IDEXECUCAOORCAMENTARIA ");
		sqlSIACE.append("        GROUP BY MESEXECUCAOORCAMENTARIA1, ");
		sqlSIACE.append("          IDDAPRESTACAO ");
		sqlSIACE.append("        ORDER BY MESEXECUCAOORCAMENTARIA1 ");
		sqlSIACE.append("        ) ");
		sqlSIACE.append("      WHERE IDDAEXECUCAORESTOSAPAGAR     = EXECUCAORESTOSAPAGAR.ID ");
		sqlSIACE.append("      AND RESTOAPAGARANTERIOR.VINCULADOA = 2 ");
		sqlSIACE.append("      ), ");
		sqlSIACE.append("      (SELECT ( ");
		sqlSIACE.append("        CASE ");
		sqlSIACE.append("          WHEN SUM(ITEMRESTOAPAGAR.VALORINSCRITO-ITEMRESTOAPAGAR.VALORCANCELADO-ITEMRESTOAPAGAR.VALORPAGO) IS NULL ");
		sqlSIACE.append("          THEN 0.0 ");
		sqlSIACE.append("          ELSE SUM(ITEMRESTOAPAGAR.VALORINSCRITO-ITEMRESTOAPAGAR.VALORCANCELADO-ITEMRESTOAPAGAR.VALORPAGO) ");
		sqlSIACE.append("        END ) AS RESTOAPAGARCAM ");
		sqlSIACE.append("      FROM EXECUCAORESTOSAPAGAR ");
		sqlSIACE.append("      INNER JOIN RESTOAPAGARANTERIOR ");
		sqlSIACE.append("      ON RESTOAPAGARANTERIOR.IDEXECUCAORESTOSAPAGAR = EXECUCAORESTOSAPAGAR.ID ");
		sqlSIACE.append("      INNER JOIN ITEMRESTOAPAGAR ");
		sqlSIACE.append("      ON RESTOAPAGARANTERIOR.IDITEMRESTOAPAGARPROCESSADO = ITEMRESTOAPAGAR.ID, ");
		sqlSIACE.append("        (SELECT MAX(EXECUCAOBISEMESTRAL.IDEXECUCAORESTOSAPAGAR) IDDAEXECUCAORESTOSAPAGAR, ");
		sqlSIACE.append("          MESEXECUCAOORCAMENTARIA1, ");
		sqlSIACE.append("          IDDAPRESTACAO ");
		sqlSIACE.append("        FROM EXECUCAOBISEMESTRAL, ");
		sqlSIACE.append("          (SELECT DISTINCT EXECUCAOORCAMENTARIA.ID AS IDDAEXECUCAOORCAMENTARIA, ");
		sqlSIACE.append("            EXECUCAOORCAMENTARIA.MES               AS MESEXECUCAOORCAMENTARIA1, ");
		sqlSIACE.append("            MUNICIPIO.NOME                         AS NOMEMUNICIPIO, ");
		sqlSIACE.append("            IDDAPRESTACAO ");
		sqlSIACE.append("          FROM MUNICIPIO ");
		sqlSIACE.append("          INNER JOIN ENTIDADEOUORGAOAP ");
		sqlSIACE.append("          ON MUNICIPIO.IDPREFEITURA = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("          INNER JOIN PRESTACAO ");
		sqlSIACE.append("          ON PRESTACAO.IDENTIDADEOUORGAOAP = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("          INNER JOIN EXECUCAOORCAMENTARIA ");
		sqlSIACE.append("          ON PRESTACAO.ID = EXECUCAOORCAMENTARIA.IDPRESTACAOLRFEXECUTIVO, ");
		sqlSIACE.append("            (SELECT PRESTACAO.ID IDDAPRESTACAO, ");
		sqlSIACE.append("              MAX(REMESSALRF.DATAENVIO)      AS DATARECEBIMENTO, ");
		sqlSIACE.append("              MAX(REMESSALRF.DATAPUBLICACAO) AS DATAPUBLICACAO ");
		sqlSIACE.append("            FROM MUNICIPIO ");
		sqlSIACE.append("            INNER JOIN ENTIDADEOUORGAOAP ");
		sqlSIACE.append("            ON MUNICIPIO.IDPREFEITURA = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("            INNER JOIN PRESTACAO ");
		sqlSIACE.append("            ON PRESTACAO.IDENTIDADEOUORGAOAP = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("            INNER JOIN REMESSALRF ");
		sqlSIACE.append("            ON PRESTACAO.ID = REMESSALRF.IDPRESTACAO, ");
		sqlSIACE.append("              DATALIMITE ");
		sqlSIACE.append("            WHERE REMESSALRF.DTBASE = ").append(dtBase);
		sqlSIACE.append("               ");
		sqlSIACE.append("            AND REMESSALRF.DTBASE = DATALIMITE.DTBASE ");
		sqlSIACE.append("            AND MUNICIPIO.CODIGOIBGE = ").append(codigoIBGE);
		sqlSIACE.append("               ");
		sqlSIACE.append("            GROUP BY PRESTACAO.ID ");
		sqlSIACE.append("            ) ");
		sqlSIACE.append("          WHERE IDDAPRESTACAO = PRESTACAO.ID ");
		sqlSIACE.append("          AND PRESTACAO.EXERCICIO      =  ").append(numAno);
		sqlSIACE.append("          AND EXECUCAOORCAMENTARIA.MES = 12 ");
		sqlSIACE.append("          ORDER BY EXECUCAOORCAMENTARIA.MES ");
		sqlSIACE.append("          ) ");
		sqlSIACE.append("        WHERE IDDAEXECUCAOORCAMENTARIA = EXECUCAOBISEMESTRAL.IDEXECUCAOORCAMENTARIA ");
		sqlSIACE.append("        GROUP BY MESEXECUCAOORCAMENTARIA1, ");
		sqlSIACE.append("          IDDAPRESTACAO ");
		sqlSIACE.append("        ORDER BY MESEXECUCAOORCAMENTARIA1 ");
		sqlSIACE.append("        ) ");
		sqlSIACE.append("      WHERE IDDAEXECUCAORESTOSAPAGAR     = EXECUCAORESTOSAPAGAR.ID ");
		sqlSIACE.append("      AND RESTOAPAGARANTERIOR.VINCULADOA = 3 ");
		sqlSIACE.append("      ), ");
		sqlSIACE.append("      (SELECT ( ");
		sqlSIACE.append("        CASE ");
		sqlSIACE.append("          WHEN SUM(ITEMRESTOAPAGAR.VALORINSCRITO-ITEMRESTOAPAGAR.VALORCANCELADO-ITEMRESTOAPAGAR.VALORPAGO) IS NULL ");
		sqlSIACE.append("          THEN 0.0 ");
		sqlSIACE.append("          ELSE SUM(ITEMRESTOAPAGAR.VALORINSCRITO-ITEMRESTOAPAGAR.VALORCANCELADO-ITEMRESTOAPAGAR.VALORPAGO) ");
		sqlSIACE.append("        END ) AS RESTOAPAGARIPP ");
		sqlSIACE.append("      FROM EXECUCAORESTOSAPAGAR ");
		sqlSIACE.append("      INNER JOIN RESTOAPAGARANTERIOR ");
		sqlSIACE.append("      ON RESTOAPAGARANTERIOR.IDEXECUCAORESTOSAPAGAR = EXECUCAORESTOSAPAGAR.ID ");
		sqlSIACE.append("      INNER JOIN ITEMRESTOAPAGAR ");
		sqlSIACE.append("      ON RESTOAPAGARANTERIOR.IDITEMRESTOAPAGARPROCESSADO = ITEMRESTOAPAGAR.ID, ");
		sqlSIACE.append("        (SELECT MAX(EXECUCAOBISEMESTRAL.IDEXECUCAORESTOSAPAGAR) IDDAEXECUCAORESTOSAPAGAR, ");
		sqlSIACE.append("          MESEXECUCAOORCAMENTARIA1, ");
		sqlSIACE.append("          IDDAPRESTACAO ");
		sqlSIACE.append("        FROM EXECUCAOBISEMESTRAL, ");
		sqlSIACE.append("          (SELECT DISTINCT EXECUCAOORCAMENTARIA.ID AS IDDAEXECUCAOORCAMENTARIA, ");
		sqlSIACE.append("            EXECUCAOORCAMENTARIA.MES               AS MESEXECUCAOORCAMENTARIA1, ");
		sqlSIACE.append("            MUNICIPIO.NOME                         AS NOMEMUNICIPIO, ");
		sqlSIACE.append("            IDDAPRESTACAO ");
		sqlSIACE.append("          FROM MUNICIPIO ");
		sqlSIACE.append("          INNER JOIN ENTIDADEOUORGAOAP ");
		sqlSIACE.append("          ON MUNICIPIO.IDPREFEITURA = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("          INNER JOIN PRESTACAO ");
		sqlSIACE.append("          ON PRESTACAO.IDENTIDADEOUORGAOAP = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("          INNER JOIN EXECUCAOORCAMENTARIA ");
		sqlSIACE.append("          ON PRESTACAO.ID = EXECUCAOORCAMENTARIA.IDPRESTACAOLRFEXECUTIVO, ");
		sqlSIACE.append("            (SELECT PRESTACAO.ID IDDAPRESTACAO, ");
		sqlSIACE.append("              MAX(REMESSALRF.DATAENVIO)      AS DATARECEBIMENTO, ");
		sqlSIACE.append("              MAX(REMESSALRF.DATAPUBLICACAO) AS DATAPUBLICACAO ");
		sqlSIACE.append("            FROM MUNICIPIO ");
		sqlSIACE.append("            INNER JOIN ENTIDADEOUORGAOAP ");
		sqlSIACE.append("            ON MUNICIPIO.IDPREFEITURA = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("            INNER JOIN PRESTACAO ");
		sqlSIACE.append("            ON PRESTACAO.IDENTIDADEOUORGAOAP = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("            INNER JOIN REMESSALRF ");
		sqlSIACE.append("            ON PRESTACAO.ID = REMESSALRF.IDPRESTACAO, ");
		sqlSIACE.append("              DATALIMITE ");
		sqlSIACE.append("            WHERE REMESSALRF.DTBASE = ").append(dtBase);
		sqlSIACE.append("               ");
		sqlSIACE.append("            AND REMESSALRF.DTBASE = DATALIMITE.DTBASE ");
		sqlSIACE.append("            AND MUNICIPIO.CODIGOIBGE = ").append(codigoIBGE);
		sqlSIACE.append("               ");
		sqlSIACE.append("            GROUP BY PRESTACAO.ID ");
		sqlSIACE.append("            ) ");
		sqlSIACE.append("          WHERE IDDAPRESTACAO = PRESTACAO.ID ");
		sqlSIACE.append("          AND PRESTACAO.EXERCICIO      =  ").append(numAno);
		sqlSIACE.append("          AND EXECUCAOORCAMENTARIA.MES = 12 ");
		sqlSIACE.append("          ORDER BY EXECUCAOORCAMENTARIA.MES ");
		sqlSIACE.append("          ) ");
		sqlSIACE.append("        WHERE IDDAEXECUCAOORCAMENTARIA = EXECUCAOBISEMESTRAL.IDEXECUCAOORCAMENTARIA ");
		sqlSIACE.append("        GROUP BY MESEXECUCAOORCAMENTARIA1, ");
		sqlSIACE.append("          IDDAPRESTACAO ");
		sqlSIACE.append("        ORDER BY MESEXECUCAOORCAMENTARIA1 ");
		sqlSIACE.append("        ) ");
		sqlSIACE.append("      WHERE IDDAEXECUCAORESTOSAPAGAR     = EXECUCAORESTOSAPAGAR.ID ");
		sqlSIACE.append("      AND RESTOAPAGARANTERIOR.VINCULADOA = 4 ");
		sqlSIACE.append("      ) ");
		sqlSIACE.append("    WHERE GESTAOFISCAL.IDPRESTACAOLRF = IDDAPRESTACAO ");
		sqlSIACE.append("    AND RESULTADONOMINAL.ID           = IDDORESULTADONOMINAL ");
		sqlSIACE.append("    AND GESTAOFISCAL.MES              = 12 ");
		sqlSIACE.append("    ) ");
		sqlSIACE.append("  GROUP BY NOMEMUNICIPIO, ");
		sqlSIACE.append("    DATARECEBIMENTO, ");
		sqlSIACE.append("    DATAPUBLICACAO, ");
		sqlSIACE.append("    RESTOAPAGAR, ");
		sqlSIACE.append("    SALDOPRECATORIO, ");
		sqlSIACE.append("    INSCRICOESRESTOAPAGAR, ");
		sqlSIACE.append("    SUBTRACAORESULTADONOMINAL, ");
		sqlSIACE.append("    ARO, ");
		sqlSIACE.append("    DEMONSTRATIVOOPCREDITOEXEC, ");
		sqlSIACE.append("    CONCESSAOGARANTIA, ");
		sqlSIACE.append("    DIVIDACONSOLIDADA ");
		sqlSIACE.append("  ORDER BY NOMEMUNICIPIO ASC ");
		sqlSIACE.append("  ), ");
		sqlSIACE.append("  (SELECT NOMEMUNICIPIO1, ");
		sqlSIACE.append("    DATARECEBIMENTO1, ");
		sqlSIACE.append("    SUM(VALORIPTU)  AS IPTUPREVISTA, ");
		sqlSIACE.append("    SUM(VALORISSQN) AS ISSQNPREVISTA, ");
		sqlSIACE.append("    SUM(VALORITBI)  AS ITBIPREVISTA, ");
		sqlSIACE.append("    SUM(VALORIRRF)  AS IRRFPREVISTA ");
		sqlSIACE.append("  FROM ");
		sqlSIACE.append("    (SELECT NOMEMUNICIPIO1, ");
		sqlSIACE.append("      MESEXECUCAOORCAMENTARIA, ");
		sqlSIACE.append("      DATARECEBIMENTO1, ");
		sqlSIACE.append("      RECEITAIMPOSTOS.VALORIPTU  AS VALORIPTU, ");
		sqlSIACE.append("      RECEITAIMPOSTOS.VALORIRRF  AS VALORIRRF, ");
		sqlSIACE.append("      RECEITAIMPOSTOS.VALORISSQN AS VALORISSQN, ");
		sqlSIACE.append("      RECEITAIMPOSTOS.VALORITBI  AS VALORITBI ");
		sqlSIACE.append("    FROM RECEITAIMPOSTOS ");
		sqlSIACE.append("    INNER JOIN RECEITATRIBUTARIA ");
		sqlSIACE.append("    ON RECEITATRIBUTARIA.IDRECEITAIMPOSTOS = RECEITAIMPOSTOS.ID ");
		sqlSIACE.append("    INNER JOIN RECEITACORRENTE ");
		sqlSIACE.append("    ON RECEITACORRENTE.IDRECEITATRIBUTARIA = RECEITATRIBUTARIA.ID ");
		sqlSIACE.append("    INNER JOIN EXECUCAORECEITA ");
		sqlSIACE.append("    ON EXECUCAORECEITA.ID = RECEITACORRENTE.IDEXECUCAORECEITA, ");
		sqlSIACE.append("      (SELECT MAX(EXECUCAOBIMESTRAL.IDEXECUCAORECEITA) IDDAEXECUCAORECEITA, ");
		sqlSIACE.append("        NOMEMUNICIPIO1, ");
		sqlSIACE.append("        MESEXECUCAOORCAMENTARIA, ");
		sqlSIACE.append("        DATARECEBIMENTO1 ");
		sqlSIACE.append("      FROM EXECUCAOBIMESTRAL, ");
		sqlSIACE.append("        ( SELECT DISTINCT EXECUCAOORCAMENTARIA.ID AS IDDAEXECUCAOORCAMENTARIA, ");
		sqlSIACE.append("          EXECUCAOORCAMENTARIA.MES                AS MESEXECUCAOORCAMENTARIA, ");
		sqlSIACE.append("          MUNICIPIO.NOME                          AS NOMEMUNICIPIO1, ");
		sqlSIACE.append("          DATARECEBIMENTO1 ");
		sqlSIACE.append("        FROM MUNICIPIO ");
		sqlSIACE.append("        INNER JOIN ENTIDADEOUORGAOAP ");
		sqlSIACE.append("        ON MUNICIPIO.IDPREFEITURA = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("        INNER JOIN PRESTACAO ");
		sqlSIACE.append("        ON PRESTACAO.IDENTIDADEOUORGAOAP = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("        INNER JOIN EXECUCAOORCAMENTARIA ");
		sqlSIACE.append("        ON PRESTACAO.ID = EXECUCAOORCAMENTARIA.IDPRESTACAOLRFEXECUTIVO, ");
		sqlSIACE.append("          (SELECT PRESTACAO.ID IDDAPRESTACAO, ");
		sqlSIACE.append("            MAX(REMESSALRF.DATAENVIO) AS DATARECEBIMENTO1 ");
		sqlSIACE.append("          FROM MUNICIPIO ");
		sqlSIACE.append("          INNER JOIN ENTIDADEOUORGAOAP ");
		sqlSIACE.append("          ON MUNICIPIO.IDPREFEITURA = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("          INNER JOIN PRESTACAO ");
		sqlSIACE.append("          ON PRESTACAO.IDENTIDADEOUORGAOAP = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("          INNER JOIN REMESSALRF ");
		sqlSIACE.append("          ON PRESTACAO.ID = REMESSALRF.IDPRESTACAO, ");
		sqlSIACE.append("            DATALIMITE ");
		sqlSIACE.append("          WHERE REMESSALRF.DTBASE = ").append(dtBase);
		sqlSIACE.append("             ");
		sqlSIACE.append("          AND REMESSALRF.DTBASE = DATALIMITE.DTBASE ");
		sqlSIACE.append("          AND MUNICIPIO.CODIGOIBGE = ").append(codigoIBGE);
		sqlSIACE.append("             ");
		sqlSIACE.append("          GROUP BY PRESTACAO.ID ");
		sqlSIACE.append("          ) ");
		sqlSIACE.append("        WHERE IDDAPRESTACAO = PRESTACAO.ID ");
		sqlSIACE.append("        AND PRESTACAO.EXERCICIO =  ").append(numAno);
		sqlSIACE.append("        ORDER BY EXECUCAOORCAMENTARIA.MES ");
		sqlSIACE.append("        ) ");
		sqlSIACE.append("      WHERE IDDAEXECUCAOORCAMENTARIA = EXECUCAOBIMESTRAL.IDEXECUCAOORCAMENTARIA ");
		sqlSIACE.append("      GROUP BY NOMEMUNICIPIO1, ");
		sqlSIACE.append("        MESEXECUCAOORCAMENTARIA, ");
		sqlSIACE.append("        DATARECEBIMENTO1 ");
		sqlSIACE.append("      ORDER BY MESEXECUCAOORCAMENTARIA ");
		sqlSIACE.append("      ) ");
		sqlSIACE.append("    WHERE EXECUCAORECEITA.ID        = IDDAEXECUCAORECEITA ");
		sqlSIACE.append("    AND RECEITACORRENTE.TIPORECEITA = 3 ");
		sqlSIACE.append("    ) ");
		sqlSIACE.append("  GROUP BY NOMEMUNICIPIO1, ");
		sqlSIACE.append("    DATARECEBIMENTO1 ");
		sqlSIACE.append("  ORDER BY NOMEMUNICIPIO1 ASC ");
		sqlSIACE.append("  ), ");
		sqlSIACE.append("  (SELECT SUM(RECEITACORRENTELIQMENSALPL) AS RECEITACORRENTELIQPL, ");
		sqlSIACE.append("    SUM(DESPESAMENSALTOTALPESSOALPL)      AS DESPESATOTALPESSOALPL ");
		sqlSIACE.append("  FROM ");
		sqlSIACE.append("    (SELECT DISTINCT ITEMCOMPARATIVOPL.RECEITACORRENTELIQUIDA RECEITACORRENTELIQMENSALPL, ");
		sqlSIACE.append("      (DESPESAMENSALPESSOAL.VENCIMENTOSVANTAGENS +DESPESAMENSALPESSOAL.INATIVOS +DESPESAMENSALPESSOAL.PENSIONISTAS +DESPESAMENSALPESSOAL.SALARIOFAMILIA +DESPESAMENSALPESSOALCAM.SUBSIDIOVEREADORES +DESPESAMENSALPESSOAL.OBRIGACOESPATRONAIS +DESPESAMENSALPESSOAL.REPASSEPATRONAL +DESPESAMENSALPESSOAL.SENTENCASJUDICIARIAS +DESPESAMENSALPESSOAL.OUTRASDESPESASPESSOAL +DESPESAMENSALPESSOAL.DESPESASANTERIORES +DESPESAMENSALPESSOAL.DESPESASANTCORRESPONDENTE +DESPESAMENSALPESSOAL.DESPESASANTERIORESCOMPETENCIA -DESPESAMENSALPESSOAL.INATIVOS -DESPESAMENSALPESSOAL.PENSIONISTAS -DESPESAMENSALPESSOAL.INDENIZACOESDEMISSAO -DESPESAMENSALPESSOAL.INCENTIVOSDEMISSAOVOLUNTARIA -DESPESAMENSALPESSOAL.SENTENCASJUDICIARIASANTERIORES -DESPESAMENSALPESSOAL.DESPESASANTCORRESPONDENTE -DESPESAMENSALPESSOAL.DESPESASANTERIORESEXCLUSAO ) AS DESPESAMENSALTOTALPESSOALPL, ");
		sqlSIACE.append("      GESTAOFISCAL.MES MES ");
		sqlSIACE.append("    FROM GESTAOFISCAL ");
		sqlSIACE.append("    INNER JOIN ITEMCOMPARATIVOPL ");
		sqlSIACE.append("    ON ITEMCOMPARATIVOPL.ID = GESTAOFISCAL.IDITEMCOMPARATIVO ");
		sqlSIACE.append("    INNER JOIN DESPESAMENSALPESSOAL ");
		sqlSIACE.append("    ON DESPESAMENSALPESSOAL.ID = IDDESPESAMENSALPESSOAL ");
		sqlSIACE.append("    INNER JOIN DESPESAMENSALPESSOALCAM ");
		sqlSIACE.append("    ON DESPESAMENSALPESSOALCAM.ID = DESPESAMENSALPESSOAL.ID, ");
		sqlSIACE.append("      (SELECT PRESTACAO.ID IDDAPRESTACAO, ");
		sqlSIACE.append("        MAX(REMESSALRF.DATAENVIO) AS DATARECEBIMENTO ");
		sqlSIACE.append("      FROM MUNICIPIO ");
		sqlSIACE.append("      INNER JOIN ENTIDADEOUORGAOAP ");
		sqlSIACE.append("      ON MUNICIPIO.IDCAMARAVEREADORES = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("      INNER JOIN PRESTACAO ");
		sqlSIACE.append("      ON PRESTACAO.IDENTIDADEOUORGAOAP = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("      INNER JOIN REMESSALRF ");
		sqlSIACE.append("      ON PRESTACAO.ID = REMESSALRF.IDPRESTACAO, ");
		sqlSIACE.append("        DATALIMITE ");
		sqlSIACE.append("      WHERE REMESSALRF.DTBASE = ").append(dtBase);
		sqlSIACE.append("         ");
		sqlSIACE.append("      AND REMESSALRF.DTBASE = DATALIMITE.DTBASE ");
		sqlSIACE.append("      AND MUNICIPIO.CODIGOIBGE = ").append(codigoIBGE);
		sqlSIACE.append("         ");
		sqlSIACE.append("      GROUP BY PRESTACAO.ID ");
		sqlSIACE.append("      ) ");
		sqlSIACE.append("    WHERE GESTAOFISCAL.IDPRESTACAOLRF = IDDAPRESTACAO ");
		sqlSIACE.append("    ORDER BY GESTAOFISCAL.MES ");
		sqlSIACE.append("    ) ");
		sqlSIACE.append("  ), ");
		sqlSIACE.append("  (SELECT DISTINCT (DISPONIBILIDADEFINANCEIRA.VALORCAIXA +DISPONIBILIDADEFINANCEIRA.VALORBANCOMOVIMENTO +DISPONIBILIDADEFINANCEIRA.VALORBANCOVINCULADAS +DISPONIBILIDADEFINANCEIRA.VALORAPLICFINANCEIRAS +DISPONIBILIDADEFINANCEIRA.VALORAPLICFINANCRECVINC ) AS DISPFINANCEIRAPL, ");
		sqlSIACE.append("    (INSCRICAORESTOSAPAGAR.VALORPROCESSADO               +INSCRICAORESTOSAPAGAR.VALORNAOPROCESSADO )                                                                                                                                                          AS VALORPROCENAOPROCPL ");
		sqlSIACE.append("  FROM GESTAOFISCAL ");
		sqlSIACE.append("  INNER JOIN DISPONIBILIDADEFINANCEIRA ");
		sqlSIACE.append("  ON DISPONIBILIDADEFINANCEIRA.ID = GESTAOFISCAL.IDDISPONIBILIDADEFINANCEIRA ");
		sqlSIACE.append("  INNER JOIN INSCRICAORESTOSAPAGAR ");
		sqlSIACE.append("  ON INSCRICAORESTOSAPAGAR.ID = GESTAOFISCAL.IDINSCRICAORESTOSAPAGAR, ");
		sqlSIACE.append("    (SELECT PRESTACAO.ID IDDAPRESTACAO, ");
		sqlSIACE.append("      MAX(REMESSALRF.DATAENVIO) AS DATARECEBIMENTO ");
		sqlSIACE.append("    FROM MUNICIPIO ");
		sqlSIACE.append("    INNER JOIN ENTIDADEOUORGAOAP ");
		sqlSIACE.append("    ON MUNICIPIO.IDCAMARAVEREADORES = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("    INNER JOIN PRESTACAO ");
		sqlSIACE.append("    ON PRESTACAO.IDENTIDADEOUORGAOAP = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("    INNER JOIN REMESSALRF ");
		sqlSIACE.append("    ON PRESTACAO.ID = REMESSALRF.IDPRESTACAO, ");
		sqlSIACE.append("      DATALIMITE ");
		sqlSIACE.append("    WHERE REMESSALRF.DTBASE = ").append(dtBase);
		sqlSIACE.append("       ");
		sqlSIACE.append("    AND REMESSALRF.DTBASE = DATALIMITE.DTBASE ");
		sqlSIACE.append("    AND MUNICIPIO.CODIGOIBGE = ").append(codigoIBGE);
		sqlSIACE.append("       ");
		sqlSIACE.append("    GROUP BY PRESTACAO.ID ");
		sqlSIACE.append("    ) ");
		sqlSIACE.append("  WHERE GESTAOFISCAL.IDPRESTACAOLRF = IDDAPRESTACAO ");
		sqlSIACE.append("  AND GESTAOFISCAL.MES              = 12 ");
		sqlSIACE.append("  ORDER BY GESTAOFISCAL.MES ");
		sqlSIACE.append("  ), ");
		sqlSIACE.append("  (SELECT DISTINCT (DISPONIBILIDADEFINANCEIRA.VALORCAIXA +DISPONIBILIDADEFINANCEIRA.VALORCAIXARPPSAS +DISPONIBILIDADEFINANCEIRA.VALORBANCOMOVIMENTO +DISPONIBILIDADEFINANCEIRA.VALORBANCOMOVIMENTORPPSAS +DISPONIBILIDADEFINANCEIRA.VALORBANCOVINCULADAS +DISPONIBILIDADEFINANCEIRA.VALORBANCOVINCULADASRPPSAS +DISPONIBILIDADEFINANCEIRA.VALORAPLICFINANCEIRAS +DISPONIBILIDADEFINANCEIRA.VALORAPLICFINANCEIRASRPPSAS +DISPONIBILIDADEFINANCEIRA.VALORAPLICFINANCRECVINC +DISPONIBILIDADEFINANCEIRA.VALORAPLICFINANCRECVINCRPPSAS ) AS DISPFINANCEIRAPE, ");
		sqlSIACE.append("    (INSCRICAORESTOSAPAGAR.VALORPROCESSADO               +INSCRICAORESTOSAPAGAR.VALORNAOPROCESSADO )                                                                                                                                                                                                                                                                                                                                                                                                                                 AS VALORPROCENAOPROCPE ");
		sqlSIACE.append("  FROM GESTAOFISCAL ");
		sqlSIACE.append("  INNER JOIN DISPONIBILIDADEFINANCEIRA ");
		sqlSIACE.append("  ON DISPONIBILIDADEFINANCEIRA.ID = GESTAOFISCAL.IDDISPONIBILIDADEFINANCEIRA ");
		sqlSIACE.append("  INNER JOIN INSCRICAORESTOSAPAGAR ");
		sqlSIACE.append("  ON INSCRICAORESTOSAPAGAR.ID = GESTAOFISCAL.IDINSCRICAORESTOSAPAGAR, ");
		sqlSIACE.append("    (SELECT PRESTACAO.ID IDDAPRESTACAO, ");
		sqlSIACE.append("      MAX(REMESSALRF.DATAENVIO) AS DATARECEBIMENTO ");
		sqlSIACE.append("    FROM MUNICIPIO ");
		sqlSIACE.append("    INNER JOIN ENTIDADEOUORGAOAP ");
		sqlSIACE.append("    ON MUNICIPIO.IDPREFEITURA = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("    INNER JOIN PRESTACAO ");
		sqlSIACE.append("    ON PRESTACAO.IDENTIDADEOUORGAOAP = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("    INNER JOIN REMESSALRF ");
		sqlSIACE.append("    ON PRESTACAO.ID = REMESSALRF.IDPRESTACAO, ");
		sqlSIACE.append("      DATALIMITE ");
		sqlSIACE.append("    WHERE REMESSALRF.DTBASE = ").append(dtBase);
		sqlSIACE.append("       ");
		sqlSIACE.append("    AND REMESSALRF.DTBASE = DATALIMITE.DTBASE ");
		sqlSIACE.append("    AND MUNICIPIO.CODIGOIBGE = ").append(codigoIBGE);
		sqlSIACE.append("       ");
		sqlSIACE.append("    GROUP BY PRESTACAO.ID ");
		sqlSIACE.append("    ) ");
		sqlSIACE.append("  WHERE GESTAOFISCAL.IDPRESTACAOLRF = IDDAPRESTACAO ");
		sqlSIACE.append("  AND GESTAOFISCAL.MES              = 12 ");
		sqlSIACE.append("  ORDER BY GESTAOFISCAL.MES ");
		sqlSIACE.append("  ), ");
		sqlSIACE.append("  (SELECT ( ");
		sqlSIACE.append("    CASE ");
		sqlSIACE.append("      WHEN (OPCAOSEMESTRALIDADE.TIPO        = 3 ");
		sqlSIACE.append("      AND STATUSOPCAOSEMESTRALIDADE.TEMOPCAO='S') ");
		sqlSIACE.append("      THEN 'Optante' ");
		sqlSIACE.append("      WHEN (OPCAOSEMESTRALIDADE.TIPO        = 3 ");
		sqlSIACE.append("      AND STATUSOPCAOSEMESTRALIDADE.TEMOPCAO='N') ");
		sqlSIACE.append("      THEN 'Perdeu o direito de optar' ");
		sqlSIACE.append("      ELSE 'Não optante' ");
		sqlSIACE.append("    END ) AS OPTANTE ");
		sqlSIACE.append("  FROM MUNICIPIO ");
		sqlSIACE.append("  INNER JOIN ENTIDADEOUORGAOAP ");
		sqlSIACE.append("  ON MUNICIPIO.IDPREFEITURA = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("  INNER JOIN OPCAOSEMESTRALIDADE ");
		sqlSIACE.append("  ON OPCAOSEMESTRALIDADE.IDENTIDADEOUORGAOAP = ENTIDADEOUORGAOAP.ID ");
		sqlSIACE.append("  INNER JOIN STATUSOPCAOSEMESTRALIDADE ");
		sqlSIACE.append("  ON STATUSOPCAOSEMESTRALIDADE.IDOPCAOSEMESTRALIDADE = OPCAOSEMESTRALIDADE.ID ");
		sqlSIACE.append("  WHERE STATUSOPCAOSEMESTRALIDADE.DTBASE = ").append(dtBase);
		sqlSIACE.append("     ");
		sqlSIACE.append("  AND MUNICIPIO.CODIGOIBGE = ").append(codigoIBGE);
		sqlSIACE.append("     ");
		sqlSIACE.append("  )");
		return sqlSIACE;
	}

	@SuppressWarnings("rawtypes")
	public void setDadosCertidaoLimites(CertidaoLimites certidao){
		
    	String numAno = certidao.getNumAnoRef().toString();
		String dtBase = "'31/12/" + numAno + "'";
		String codigoIBGE = "'" + certidao.getCodMunicipio().toString() + "'";
		
		StringBuilder sqlSIACE = getSQLRelatorioSIACE(numAno, dtBase, codigoIBGE);
		
		Query query = entityManagerSIACE.createNativeQuery(sqlSIACE.toString());
		List resultList = query.getResultList();
		if(resultList != null && !resultList.isEmpty()){
			
			Object[] lrf = (Object[]) resultList.get(0);
			certidao.setNomeMunicipio(lrf[0].toString());
			
			certidao.setDscOpcaoSemestralidade(lrf[2].toString()); //0
			
			certidao.setPctDespesaExecutivo((BigDecimal)lrf[3]); //1
			certidao.setPctDespesaLegislativo((BigDecimal)lrf[4]); //1 
			certidao.setPctDespesaTotal((BigDecimal)lrf[5]); //1
			
			certidao.setDatPublicacaoExecutivo((Timestamp)lrf[1]); //2
			
			certidao.setPctDividaConsExecutivo((BigDecimal)lrf[6]); //3
			certidao.setVlrDividaConsLrf((BigDecimal) lrf[20]); //3
			
			
			certidao.setPctConcGarantExecutivo((BigDecimal)lrf[9]); //4
			
			certidao.setPctOperCredExecutivo((BigDecimal)lrf[8]); //5
			certidao.setPctOperCredRealExec((BigDecimal)lrf[11]); //5
			
			certidao.setPctAroExecutivo((BigDecimal)lrf[7]); //6
			
			certidao.setDscResultadoRpps(lrf[10].toString()); //7
			
			//8
			certidao.setVlrIPTUPrevista((BigDecimal) lrf[12]);
			certidao.setVlrIPTURealizada((BigDecimal)lrf[13]);
			certidao.setVlrISSQNPrevista((BigDecimal)lrf[14]);
			certidao.setVlrISSQNRealizada((BigDecimal)lrf[15]);
			certidao.setVlrITBIPrevista((BigDecimal)lrf[16]);
			certidao.setVlrITBIRealizada((BigDecimal)lrf[17]);
			certidao.setVlrIRRFPrevista((BigDecimal)lrf[18]);
			certidao.setVlrIRRFRealizada((BigDecimal)lrf[19]);
			
			if(certidao.getVlrIPTURealizada().doubleValue() == 0D 
					|| certidao.getVlrISSQNRealizada().doubleValue() == 0D
					|| certidao.getVlrITBIRealizada().doubleValue() == 0D
					|| certidao.getVlrIRRFRealizada().doubleValue() == 0D){
				certidao.setDscImpCompNaoArrecadados(certidao.getImpostosNaoArrecadado());
			}else{
				certidao.setDscImpCompNaoArrecadados("OK");
			}
			
			if(certidao.getVlrIPTUPrevista().doubleValue() == 0D 
					|| certidao.getVlrISSQNPrevista().doubleValue() == 0D
					|| certidao.getVlrITBIPrevista().doubleValue() == 0D
					|| certidao.getVlrIRRFPrevista().doubleValue() == 0D){
				certidao.setDscImpCompNaoPrevisto(certidao.getImpostosNaoPrevisto());
			}else{
				certidao.setDscImpCompNaoPrevisto("OK");
			}
			
			certidao.setDataGeracaoCertidao(new Date());
			certidao.setIndSituacao(IndSituacaoCertidaoEnum.CONCLUIDA);
		}else{
			certidao.setIndSituacao(IndSituacaoCertidaoEnum.INDEFERIDA);
			certidao.setDataGeracaoCertidao(new Date());
			certidao.setDscIndeferidoJustificativa(Constantes.MSG_INDEFERIMENTO_SIACE);
		}
		
	}

	@Override
	@SuppressWarnings("rawtypes")
	public void setDadosCertidaoCompetenciaTributaria(CertidaoCompetenciaTributaria certidao) {
		
    	String numAno = certidao.getNumAnoRef().toString();
		String dtBase = "'31/12/" + numAno + "'";
		String codigoIBGE = "'" + certidao.getCodMunicipio().toString() + "'";

		StringBuilder sqlSIACE = getSQLRelatorioSIACE(numAno, dtBase, codigoIBGE);
		
		Query query = entityManagerSIACE.createNativeQuery(sqlSIACE.toString());
		List resultList = query.getResultList();
		if(resultList != null && !resultList.isEmpty()){
			
			Object[] lrf = (Object[]) resultList.get(0);
			BigDecimal vlrIPTUPrevista = ((BigDecimal) lrf[12]);
			BigDecimal vlrIPTURealizada = ((BigDecimal)lrf[13]);
			BigDecimal vlrISSQNPrevista = ((BigDecimal)lrf[14]);
			BigDecimal vlrISSQNRealizada = ((BigDecimal)lrf[15]);
			BigDecimal vlrITBIPrevista = ((BigDecimal)lrf[16]);
			BigDecimal vlrITBIRealizada = ((BigDecimal)lrf[17]);
			BigDecimal vlrIRRFPrevista = ((BigDecimal)lrf[18]);
			BigDecimal vlrIRRFRealizada = ((BigDecimal)lrf[19]);
			
			if(vlrIPTUPrevista.doubleValue() != 0D){
				certidao.setPrevisaoIPTU(true);
			}
			if(vlrIPTURealizada.doubleValue() != 0D){
				certidao.setArrecadacaoIPTU(true);
			}
			if(vlrISSQNPrevista.doubleValue() != 0D){
				certidao.setPrevisaoISSQN(true);
			}
			if(vlrISSQNRealizada.doubleValue() != 0D){
				certidao.setArrecadacaoISSQN(true);
			}
			if(vlrITBIPrevista.doubleValue() != 0D){
				certidao.setPrevisaoITBI(true);
			}
			if(vlrITBIRealizada.doubleValue() != 0D){
				certidao.setArrecadacaoITBI(true);
			}
			if(vlrIRRFPrevista.doubleValue() != 0D){
				certidao.setPrevisaoIRRF(true);
			}
			if(vlrIRRFRealizada.doubleValue() != 0D){
				certidao.setArrecadacaoIRRF(true);
			}

			certidao.setDscImpCompNaoArrecadados(certidao.getImpostosNaoArrecadado());
			certidao.setDscImpCompNaoPrevisto(certidao.getImpostosNaoPrevisto());
			certidao.setDataGeracaoCertidao(new Date());
			certidao.setIndSituacao(IndSituacaoCertidaoEnum.CONCLUIDA);
		}else{
			certidao.setIndSituacao(IndSituacaoCertidaoEnum.INDEFERIDA);
			certidao.setDataGeracaoCertidao(new Date());
			certidao.setDscIndeferidoJustificativa(Constantes.MSG_INDEFERIMENTO_SIACE);
		}
	}

}
