
package br.gov.mg.tce.client.sigespCalendario;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalendarioBO", targetNamespace = "http://calendariows.sigesp.tcemg/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalendarioBO {


    /**
     * 
     * @param quantDias
     * @param dataRef
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod
    @WebResult(name = "data", targetNamespace = "")
    @RequestWrapper(localName = "adicionaDiasUteis", targetNamespace = "http://calendariows.sigesp.tcemg/", className = "br.gov.mg.tce.client.sigespCalendario.AdicionaDiasUteis")
    @ResponseWrapper(localName = "adicionaDiasUteisResponse", targetNamespace = "http://calendariows.sigesp.tcemg/", className = "br.gov.mg.tce.client.sigespCalendario.AdicionaDiasUteisResponse")
    public XMLGregorianCalendar adicionaDiasUteis(
        @WebParam(name = "dataRef", targetNamespace = "")
        XMLGregorianCalendar dataRef,
        @WebParam(name = "quantDias", targetNamespace = "")
        long quantDias);

}
