
package br.gov.mg.tce.client.sigespCalendario;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalendarioWSService", targetNamespace = "http://calendariows.sigesp.tcemg/", wsdlLocation = "http://172.30.14.23:8080/sightWebServidor-web/CalendarioBO?wsdl")
public class CalendarioWSService
    extends Service
{

    private final static URL CALENDARIOWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALENDARIOWSSERVICE_EXCEPTION;
    private final static QName CALENDARIOWSSERVICE_QNAME = new QName("http://calendariows.sigesp.tcemg/", "CalendarioWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.30.14.23:8080/sightWebServidor-web/CalendarioBO?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALENDARIOWSSERVICE_WSDL_LOCATION = url;
        CALENDARIOWSSERVICE_EXCEPTION = e;
    }

    public CalendarioWSService() {
        super(__getWsdlLocation(), CALENDARIOWSSERVICE_QNAME);
    }

    public CalendarioWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALENDARIOWSSERVICE_QNAME, features);
    }

    public CalendarioWSService(URL wsdlLocation) {
        super(wsdlLocation, CALENDARIOWSSERVICE_QNAME);
    }

    public CalendarioWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALENDARIOWSSERVICE_QNAME, features);
    }

    public CalendarioWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalendarioWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalendarioBO
     */
    @WebEndpoint(name = "CalendarioBOPort")
    public CalendarioBO getCalendarioBOPort() {
        return super.getPort(new QName("http://calendariows.sigesp.tcemg/", "CalendarioBOPort"), CalendarioBO.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalendarioBO
     */
    @WebEndpoint(name = "CalendarioBOPort")
    public CalendarioBO getCalendarioBOPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://calendariows.sigesp.tcemg/", "CalendarioBOPort"), CalendarioBO.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALENDARIOWSSERVICE_EXCEPTION!= null) {
            throw CALENDARIOWSSERVICE_EXCEPTION;
        }
        return CALENDARIOWSSERVICE_WSDL_LOCATION;
    }

}
