
package br.gov.mg.tce.client.pca.core;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IntegracaoCoreECertidaoWSService", targetNamespace = "http://integracaocore.ecertidao.tcemg/", wsdlLocation = "http://panama.tce.mg.gov.br:8080/pca-analise/IntegracaoCoreECertidaoWS?wsdl")
public class IntegracaoCoreECertidaoWSService
    extends Service
{

    private final static URL INTEGRACAOCOREECERTIDAOWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException INTEGRACAOCOREECERTIDAOWSSERVICE_EXCEPTION;
    private final static QName INTEGRACAOCOREECERTIDAOWSSERVICE_QNAME = new QName("http://integracaocore.ecertidao.tcemg/", "IntegracaoCoreECertidaoWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://panama.tce.mg.gov.br:8080/pca-analise/IntegracaoCoreECertidaoWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INTEGRACAOCOREECERTIDAOWSSERVICE_WSDL_LOCATION = url;
        INTEGRACAOCOREECERTIDAOWSSERVICE_EXCEPTION = e;
    }

    public IntegracaoCoreECertidaoWSService() {
        super(__getWsdlLocation(), INTEGRACAOCOREECERTIDAOWSSERVICE_QNAME);
    }

    public IntegracaoCoreECertidaoWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INTEGRACAOCOREECERTIDAOWSSERVICE_QNAME, features);
    }

    public IntegracaoCoreECertidaoWSService(URL wsdlLocation) {
        super(wsdlLocation, INTEGRACAOCOREECERTIDAOWSSERVICE_QNAME);
    }

    public IntegracaoCoreECertidaoWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INTEGRACAOCOREECERTIDAOWSSERVICE_QNAME, features);
    }

    public IntegracaoCoreECertidaoWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IntegracaoCoreECertidaoWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IntegracaoCoreECertidaoWS
     */
    @WebEndpoint(name = "IntegracaoCoreECertidaoWSPort")
    public IntegracaoCoreECertidaoWS getIntegracaoCoreECertidaoWSPort() {
        return super.getPort(new QName("http://integracaocore.ecertidao.tcemg/", "IntegracaoCoreECertidaoWSPort"), IntegracaoCoreECertidaoWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IntegracaoCoreECertidaoWS
     */
    @WebEndpoint(name = "IntegracaoCoreECertidaoWSPort")
    public IntegracaoCoreECertidaoWS getIntegracaoCoreECertidaoWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://integracaocore.ecertidao.tcemg/", "IntegracaoCoreECertidaoWSPort"), IntegracaoCoreECertidaoWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INTEGRACAOCOREECERTIDAOWSSERVICE_EXCEPTION!= null) {
            throw INTEGRACAOCOREECERTIDAOWSSERVICE_EXCEPTION;
        }
        return INTEGRACAOCOREECERTIDAOWSSERVICE_WSDL_LOCATION;
    }

}
