
package br.gov.mg.tce.client.sgap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProcessoTransJulgadoWS", targetNamespace = "http://processoTransJulgado.sgap.tcemg/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProcessoTransJulgadoWS {


    /**
     * 
     * @return
     *     returns java.util.List<br.gov.mg.tce.client.sgap.ListarProcessosTransJulgadosDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarProcessosTransJulgados", targetNamespace = "http://processoTransJulgado.sgap.tcemg/", className = "br.gov.mg.tce.client.sgap.ListarProcessosTransJulgados")
    @ResponseWrapper(localName = "listarProcessosTransJulgadosResponse", targetNamespace = "http://processoTransJulgado.sgap.tcemg/", className = "br.gov.mg.tce.client.sgap.ListarProcessosTransJulgadosResponse")
    public List<ListarProcessosTransJulgadosDTO> listarProcessosTransJulgados();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<br.gov.mg.tce.client.sgap.ListarProcessosTransJulgadosDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarProcessosTransJulgadosPorListaProcessos", targetNamespace = "http://processoTransJulgado.sgap.tcemg/", className = "br.gov.mg.tce.client.sgap.ListarProcessosTransJulgadosPorListaProcessos")
    @ResponseWrapper(localName = "listarProcessosTransJulgadosPorListaProcessosResponse", targetNamespace = "http://processoTransJulgado.sgap.tcemg/", className = "br.gov.mg.tce.client.sgap.ListarProcessosTransJulgadosPorListaProcessosResponse")
    public List<ListarProcessosTransJulgadosDTO> listarProcessosTransJulgadosPorListaProcessos(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Long> arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns br.gov.mg.tce.client.sgap.ListarProcessosTransJulgadosDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarProcessosTransJulgadosPorNumeroProcesso", targetNamespace = "http://processoTransJulgado.sgap.tcemg/", className = "br.gov.mg.tce.client.sgap.ListarProcessosTransJulgadosPorNumeroProcesso")
    @ResponseWrapper(localName = "listarProcessosTransJulgadosPorNumeroProcessoResponse", targetNamespace = "http://processoTransJulgado.sgap.tcemg/", className = "br.gov.mg.tce.client.sgap.ListarProcessosTransJulgadosPorNumeroProcessoResponse")
    public ListarProcessosTransJulgadosDTO listarProcessosTransJulgadosPorNumeroProcesso(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
