
package br.gov.mg.tce.client.sgap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProcessosTransJulgadoWSService", targetNamespace = "http://processoTransJulgado.sgap.tcemg/", wsdlLocation = "http://172.30.11.44:8080/sgap-ejb-1.0-SNAPSHOT/ProcessoTransJulgadoWS?wsdl")
public class ProcessosTransJulgadoWSService
    extends Service
{

    private final static URL PROCESSOSTRANSJULGADOWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROCESSOSTRANSJULGADOWSSERVICE_EXCEPTION;
    private final static QName PROCESSOSTRANSJULGADOWSSERVICE_QNAME = new QName("http://processoTransJulgado.sgap.tcemg/", "ProcessosTransJulgadoWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.30.11.44:8080/sgap-ejb-1.0-SNAPSHOT/ProcessoTransJulgadoWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROCESSOSTRANSJULGADOWSSERVICE_WSDL_LOCATION = url;
        PROCESSOSTRANSJULGADOWSSERVICE_EXCEPTION = e;
    }

    public ProcessosTransJulgadoWSService() {
        super(__getWsdlLocation(), PROCESSOSTRANSJULGADOWSSERVICE_QNAME);
    }

    public ProcessosTransJulgadoWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROCESSOSTRANSJULGADOWSSERVICE_QNAME, features);
    }

    public ProcessosTransJulgadoWSService(URL wsdlLocation) {
        super(wsdlLocation, PROCESSOSTRANSJULGADOWSSERVICE_QNAME);
    }

    public ProcessosTransJulgadoWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROCESSOSTRANSJULGADOWSSERVICE_QNAME, features);
    }

    public ProcessosTransJulgadoWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProcessosTransJulgadoWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProcessoTransJulgadoWS
     */
    @WebEndpoint(name = "ProcessoTransJulgadoWSPort")
    public ProcessoTransJulgadoWS getProcessoTransJulgadoWSPort() {
        return super.getPort(new QName("http://processoTransJulgado.sgap.tcemg/", "ProcessoTransJulgadoWSPort"), ProcessoTransJulgadoWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProcessoTransJulgadoWS
     */
    @WebEndpoint(name = "ProcessoTransJulgadoWSPort")
    public ProcessoTransJulgadoWS getProcessoTransJulgadoWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://processoTransJulgado.sgap.tcemg/", "ProcessoTransJulgadoWSPort"), ProcessoTransJulgadoWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROCESSOSTRANSJULGADOWSSERVICE_EXCEPTION!= null) {
            throw PROCESSOSTRANSJULGADOWSSERVICE_EXCEPTION;
        }
        return PROCESSOSTRANSJULGADOWSSERVICE_WSDL_LOCATION;
    }

}
